### ISSUE TITLE
Ambiguous parsing of null/empty scalars

### ISSUE THREAD

**Issue by litghost** [biojppm/rapidyaml#103]
The following documents appear to parse incorrectly.  Am I missing something?

Doc 1:
```
{test: null}
```

Results in:
```
tree.size() -> 2, correct
tree.root_id() -> 0, correct
tree.first_child(0) -> 1, correct
tree.type(1) -> 3, KEY|VAL, correct
tree.key(1) -> "test", correct
tree.val(1) -> "null", expected null value 
```

Doc 2:
```
{test: }
```

Results in:
```
tree.size() -> 2, correct
tree.root_id() -> 0, correct
tree.first_child(0) -> 1, correct
tree.type(1) -> 3, KEY|VAL, correct
tree.key(1) -> "test", correct
tree.val(1) -> "", expected null value 
```

Doc 3:
```
{test: ~}
```

Results in:
```
tree.size() -> 2, correct
tree.root_id() -> 0, correct
tree.first_child(0) -> 1, correct
tree.type(1) -> 3, KEY|VAL, correct
tree.key(1) -> "test", correct
tree.val(1) -> "", expected null value 
```

Tests that work as expected:
```
{test: "null"}
```

Results in:
```
tree.size() -> 2, correct
tree.root_id() -> 0, correct
tree.first_child(0) -> 1, correct
tree.type(1) -> 3, KEY|VAL, correct
tree.key(1) -> "test", correct
tree.val(1) -> "null", correct
```

**Comment by biojppm** [comment]
Thanks for reporting. Seems a bug indeed.

**Comment by biojppm** [comment]
@litghost is this 0.1.0 or the latest master?

**Comment by litghost** [comment]
> @litghost is this 0.1.0 or the latest master?

I was doing my testing on latest master.  I noticed that there are flags that look like they might be useful in disambiguating null from str, e.g. https://github.com/biojppm/rapidyaml/blob/bbc2c4af3b50d1b9661cad9c1a6956786b0c8882/src/c4/yml/tree.hpp#L126 or https://github.com/biojppm/rapidyaml/blob/bbc2c4af3b50d1b9661cad9c1a6956786b0c8882/src/c4/yml/tree.hpp#L60 , but I don't believe these are getting used right now?

**Comment by biojppm** [comment]
Yes, those are still a sketch. I will try to look at this soon, hopefully before the end of the week.
