### ISSUE TITLE
how to use parse?

### ISSUE THREAD

**Issue by HanG-CS** [biojppm/rapidyaml#109]
I want to use parse to read a yaml doc, but i don't know how to use this API.
eg:
    std::string file_name = "xxx";
    Tree tree = parse(file_name);
It can not work, how can I use it ???

**Comment by HanG-CS** [comment]
And can I load a  ".gz" file?

**Comment by biojppm** [comment]
This library does not parse directly from a file. You need to read the file contents to a string and then pass that string to the parser.

And no gz parsing as well. You need to decompress the contents before parsing.
