### ISSUE TITLE
csubstr Parser::_filter_block_scalar fails

### ISSUE THREAD

**Issue by chetmurphy** [biojppm/rapidyaml#113]
This error appears to occur when the last line of a file is not empty.

Just adding an empty line as the last line fixes it.

<code>
csubstr Parser::_filter_block_scalar(substr s, BlockStyle_e style, BlockChomp_e chomp, size_t indentation)
{
    _c4dbgpf("filtering block: '%.*s'", _c4prsp(s));

    RYML_ASSERT(s.ends_with('\n') || s.ends_with('\r'));  <-- fails here
</code>

when the file is:

<pre>
class: Slicer
id: slicer
name: Slicer
summary: Slices a part into layers.
description: >
     A stage that slices a part based on 'flat' surfaces
     into layers.
     &#92;&lt;br&#92;&gt;
     This stage can be used to feed a surface joint
     that is registered for a perfect fit. It uses 
     the previous stage profile to determine the 
     layers.
     &#92;&lt;br&#92;&gt; 
     Think of this stage as a step in building your own custom
     composite material.</pre>

**Comment by chetmurphy** [comment]
I don't know if it makes a different but the last block is a 

name: >
   text ...

**Comment by biojppm** [comment]
Thanks for reporting. Allow me some time to investigate.

**Comment by biojppm** [comment]
@chetmurphy I was not able to reproduce the behavior you describe. See the commit referenced above.
