### ISSUE TITLE
Question: How to iterate through individual docs of multi-doc YAML

### ISSUE THREAD

**Issue by groodt** [biojppm/rapidyaml#117]
I'm wondering how to iterate through the individual documents of a multi-doc YAML.

I have this so far:
```
        ryml::Tree tree = ryml::parse(c4::to_csubstr(value));
        c4::yml::NodeRef root = tree.rootref();

        if (tree.is_stream(root.is_doc())) {
          for(c4::yml::NodeRef node : root.children())
          {
              ryml::emit(node);
          }
        }
```

This appears to work so far.

I'm then wondering how to either convert individual nodes into json *or* how to remove the type of `DOCMAP` so that I can convert the node into JSON.

Any pointers would be greatly appreciated.

**Comment by chetmurphy** [comment]
This is the code I'm using:

<pre>
     if (_tree.is_stream(0))
     {
         int i = 0;
         ryml::NodeRef doc = _tree[i];
         while(doc.valid() && !doc.is_seed())
         {


               doc = _tree[++i];
         }
    }
</pre>           

Just remember that ryml creates a writable node, apparently called a seed, if one does not exist.  Thus the test **!doc.is_seed()**. There is nothing to read with a seed and until something is written so most methods will fail (two exceptions appear to be valid() and is_seed()).

doc |= ryml::SEQ; // now doc is valid() and available for writting.

**Comment by groodt** [comment]
> Just remember that ryml creates a writable node, apparently called a seed, if one does not exist. Thus the test **!doc.is_seed()**. There is nothing to read with a seed and until something is written most methods will fail (two exceptions appear to be valid() and is_seed()).

Got it! Thanks!

I don't suppose you would then know if it's possible to emit the individual doc `as_json`? Currently ryml will refuse to emit YAML streams as JSON.

**Comment by biojppm** [comment]
@groodt @chetmurphy Really sorry for taking so long to reply.

There was indeed a check that prevented emitting json from individual docs within a stream, which is a valid use case.

 I have fixed the check to address streams instead of docs, and added a sample on how to deal with this situation; just click on the commit above to see the details in the sample code from the quickstart. Very briefly, you do it like this:
```c++
std::string yml = R"(---
a: 0
b: 1
---
c: 2
d: 3
---
- 4
- 5
- 6
- 7
)";
ryml::Tree tree = ryml::parse(ryml::to_substr(yml));
const std::string expected_json[] = {
    R"({"a": 0,"b": 1})",
    R"({"c": 2,"d": 3})",
    R"([4,5,6,7])",
};
// using the node API:
size_t count = 0;
const ryml::NodeRef stream = tree.rootref();
assert(stream.num_children() == std::size(expected_json));
for(const ryml::NodeRef doc : stream.children())
    assert(ryml::emitrs_json<std::string>(doc) == expected_json[count++]);
// or using the lower level index API:
count = 0;
const size_t stream_id = tree.root_id();
assert(tree.num_children(stream_id) == std::size(expected_json));
for(size_t doc_id = tree.first_child(stream_id); doc_id != ryml::NONE; doc_id = tree.next_sibling(doc_id))
    assert(ryml::emitrs_json<std::string>(tree, doc_id) == expected_json[count++]);
```

@groodt there is a serious problem in waiting in the code you first posted:
```c++
if(tree.is_stream(root.is_doc())) // ERROR
   ...

// is_stream() receives a node index (ie an id), not a boolean.
// All tree methods receiving a `size_t` refer to a node id.
// In an empty tree, the above code will crash.
// The correct check is this:
size_t root_id = tree.root_id(); // this is the subject of the query
if(tree.is_stream(root_id)) // correct. pass the id of the node about which you are querying
  ...
```
