### ISSUE TITLE
 Question: Is there a reason that emitting `as_json` does not support Scalar values as the root?

### ISSUE THREAD

**Issue by groodt** [biojppm/rapidyaml#118]
From what I can tell, if emitting through `as_json`, a root Scalar value is emitted as a sequence. Is there a reason behind this?

A JSON document can have a scalar value at the root level and I *think* YAML supports this as well.

**Comment by biojppm** [comment]
@groodt This is an unintended quirk from how ryml requires any scalar to be in a container. In other words, the root cannot be a scalar, and that assumption (which in hindsight should be relaxed) is baked in a number of places throughout the code. For that reason I will not fix this for now, as it is still possible to work around the problem by emitting the scalar node directly.

HTH.
