### ISSUE TITLE
Emits invalid JSON when handling values that contain numbers

### ISSUE THREAD

**Issue by groodt** [biojppm/rapidyaml#121]
This YAML:
```yaml
 string_value: "string"
 number_value: "9001"
 broken_value: "0.30.2"
```

When parsed with this code:
```cpp
ryml::Tree tree = ryml::parse(c4::to_csubstr(value));
std::ostringstream jsonStream;
jsonStream << ryml::as_json(tree);
std::cout << jsonStream.str() << '\n';
```

Emits this JSON:
```
{"string_value": "string","number_value": 9001,"broken_value": 0.30.2}
```

This JSON is invalid. It appears that when emitting as JSON, it is attempting to coerce string values into integer types.

I've been attempting to use rapidyaml to parse kubernetes manifests and one of the issues I've run into is this implicit conversion to integers. Is there a way to prevent it? In kubernetes, there are often times where a String representation of a numeric value is required, so it would be nice if this was supported. It does seem to be part of the YAML spec that if a value is quoted in double or single quotes that it should be interpreted as a String.

**Comment by Ambrase** [comment]
Any plans to fix this?

**Comment by biojppm** [comment]
Hi @groodt & @Ambrase ,

Thanks for reporting, and sorry for the very late response. Serendipity helped here, as #132 provided just the thing to address this (thanks to @Gei0r).

I'm preparing the MR with the fix and ensuring all tests pass before merging. Hold on just a little longer.
