### ISSUE TITLE
Segfault when referencing non-existent anchor

### ISSUE THREAD

**Issue by Gei0r** [biojppm/rapidyaml#128]
`tree::resolve()` segfaults when the parsed yaml contains a reference to an anchor that does not exist.

Minimal example:
```c++
#include <ryml.hpp>

int main()
{
    const char filedata[] = "*";
    ryml::Tree tr = ryml::parse(filedata);
    tr.resolve();
}
```

**Comment by Gei0r** [comment]
The problem is that `ReferenceResolver::_lookup()` runs into `C4_NEVER_REACH()` [here](https://github.com/biojppm/rapidyaml/blob/master/src/c4/yml/tree.cpp#L1209) when the anchor is not found.

I added a pull request that introduces proper error handling.

**Comment by biojppm** [comment]
@Gei0r thanks for reporting, and thanks for submitting the fix.
