### ISSUE TITLE
fast_float needs update for using ryml in a c++20 project

### ISSUE THREAD

**Issue by Allar** [biojppm/rapidyaml#134]
Loving ryml. Trying to use it in a project I'm upgrading to c++20 from c++17, and I'm getting a bunch of link issues due to an issue in the version of fast_float rapidyaml is using.

I believe ryml is using fast_float v0.7.0, and this issue was addressed in fast_float v1.1.0

https://github.com/fastfloat/fast_float/releases

Is there any chance of upgrading the used fast_float version in ryml (and I suppose c4core?) to v1.1.0 or later?

Thanks!

**Comment by biojppm** [comment]
Thanks for the kind words, and thanks for the heads up. I'm in the process of updating fast_float but c4core is making it a bit difficult. Hold on just a little more.
