### ISSUE TITLE
warnings: empty expression statement

### ISSUE THREAD

**Issue by biojppm** [biojppm/rapidyaml#14]
joining to @dkeeney : 
tons of warnings like "empty expression statement has no effect; remove unnecessary ';' to silence this warning" may be fixed with macroses like this:
```
#define ev_idle_init(ev,cb)  do { ev_init ((ev), (cb)); ev_idle_set ((ev)); } while (0)
```

_Originally posted by @parihaaraka in https://github.com/biojppm/rapidyaml/issues/12#issuecomment-533052303_

**Comment by biojppm** [comment]
Will hide by shutting down -Wextra-semi-stmt where appropriate.

**Comment by biojppm** [comment]
Hi @parihaaraka,

I've tried compiling with pedantic + warnings as errors, but I cannot get these warnings. Can you show me logs with this error?

**Comment by parihaaraka** [comment]
i belive it's about static analyzer warnings

**Comment by biojppm** [comment]
which static analyzer?

**Comment by biojppm** [comment]
Cannot reproduce, closing. Feel free to reopen if you can provide a MVE or specify which static analyzer/compiler flags trigger this.
