### ISSUE TITLE
preprocess_json hits assertion when json strings contains closing brace

### ISSUE THREAD

**Issue by Gei0r** [biojppm/rapidyaml#142]
When preprocessing this json: `{  "A": "B}"  }` (note the `}` within the string) an assertion is hit:

```
ERROR: expected true: ss.begins_with(curr) && ss.ends_with(curr)
```
It's from [preprocess.cpp line 125](https://github.com/biojppm/rapidyaml/blob/006e9c4e2b1d43c9dc1babdc15230b29761d49eb/src/c4/yml/preprocess.cpp#L125).

In Release builds, the program runs into an endless loop.

----

Full code:

```c++
#include <ryml_std.hpp>
#include <ryml.hpp>
#include <c4/yml/preprocess.hpp>

int main()
{
    const char data[] = "{  \"A\": \"B}\"  }";

    std::string yaml = ryml::preprocess_json<std::string>(data);
    const ryml::Tree tr = ryml::parse(c4::to_csubstr(yaml));
}
```

**Comment by Gei0r** [comment]
The assertion isn't printed on release builds; instead, the program runs into an endless loop.

**Comment by biojppm** [comment]
Thanks!
