### ISSUE TITLE
A ryml::Tree instance was changed unexpectedly  after it return from a function

### ISSUE THREAD

**Issue by YK-Unit** [biojppm/rapidyaml#148]
A ryml::Tree instance was changed unexpectedly  after it return from a function. Here is the case:

**Here the case code:**
``` cpp
#include <ryml_std.hpp>
#include <ryml.hpp>

#include <iostream>
#include <fstream>
#include <filesystem>

ryml::Tree load_pubspec_tree_from_file(std::string pubspec_file_path) {
    std::ifstream pubspec_file_stream(pubspec_file_path);
    std::stringstream pubspec_string_stream;
    pubspec_string_stream << pubspec_file_stream.rdbuf();
    std::string pubspec_file_content_str = pubspec_string_stream.str();
    c4::substr pubspec_file_content_c4str = c4::to_substr(pubspec_file_content_str);

    ryml::Tree pubspec_tree = ryml::parse(pubspec_file_content_c4str);
    std::cout << "pubspec tree:\n" << pubspec_tree << std::endl;
    return pubspec_tree;
}

int main() {
    ryml::Tree pubspec_tree = load_pubspec_tree_from_file("path/to/pubspec.txt");
    std::cout << "pubspec tree(with messy code):\n" << pubspec_tree << std::endl;
}
```
**Here the pubspce.txt:**
[pubspec.txt](https://github.com/biojppm/rapidyaml/files/6950302/pubspec.txt)

**Here the code output:**
![image](https://user-images.githubusercontent.com/4953353/128622699-67336ed0-7d41-40c5-922c-ca4905db83f6.png)

**My develop env:**
```
CLion 2021.1.3
Build #CL-211.7628.27, built on July 2, 2021
Licensed to CLion Evaluator
Expiration date: August 10, 2021
Runtime version: 11.0.11+9-b1341.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: io.zhile.research.ide-eval-resetter (2.1.14)
```

**Comment by biojppm** [comment]
The tree is pointing at dangling memory. You're allocating the string inside the function and making the tree point at it. Then you return the tree but the string is deallocated when the function returns.

You need to ensure that the lifetime of the buffer exceeds the lifetime of the tree.

**Comment by biojppm** [comment]
By the way, you can use the tree's arena to store the string. If you pass a constant csubstr, it will be copied to the arena and only then it will be parsed.

**Comment by YK-Unit** [comment]
Thanks so much, I'll try your advise to modify the code ^_^
