### ISSUE TITLE
src/c4/yml/detail/atof.c

### ISSUE THREAD

**Issue by jbosboom** [biojppm/rapidyaml#16]
`src/c4/yml/detail/atof.c` declares `double atof(char* p)` but it's guarded by `#ifdef FLOATINGPT` and that doesn't seem to be defined anywhere.  `src/c4/yml/detail/strtod.hpp` also defines `atof`.  Is `atof.c` junk?

**Comment by jbosboom** [comment]
`src/c4/yml/detail/strtod.hpp` also doesn't seem to be used: the only occurrences of `strtod` are within that file, so unless you're doing something very strange it isn't being included anywhere.

The other files in `src/c4/yml/detail` are being included, though, so it seems to be just these two that are unused.

**Comment by biojppm** [comment]
Indeed, both these files are unused. They were added as possible replacements for sscanf, but in the meantime this logic was moved to [c4core low-level library](https://github.com/biojppm/c4core) and I forgot about these files here. Thanks for the heads up.

**Comment by biojppm** [comment]
Already cleaned.
