### ISSUE TITLE
Some node predicate methods are missing in the Python API

### ISSUE THREAD

**Issue by simu** [biojppm/rapidyaml#165]
In the Python API the following node predicate methods on `Tree` are missing (as I found out when trying to correctly parse `'True'` as a string)

* `is_anchor_or_ref()`
* `is_key_quoted()`
* `is_val_quoted()`
* `is_quoted()`

I'd be happy to try to create a PR adding those to the Python API.

**Comment by biojppm** [comment]
Thanks for reporting. Indeed the Python API is still very much a WIP, and definitely a PR would be welcome.
