### ISSUE TITLE
Which headers to package?

### ISSUE THREAD

**Issue by jbosboom** [biojppm/rapidyaml#17]
I'm trying to write an Arch Linux package (PKGBUILD) for rapidyaml.  I successfully built `libryml.a` and see that it includes the object files from `libc4core.a`.

Which include files should I package?  In particular, what of `extern/c4core/src` and `extern/c4core/extern/*` are used in rapidyaml's interface?

I'm not very familiar with cmake, but at least the generated Makefile doesn't have an `install` target.

**Comment by biojppm** [comment]
Yes, both libryml.a and libc4core should be packaged, along with the full source tree and extern folders from both projects.

So outside of cmake that would be done with something like the following (untested):

```bash
# libs
libs="path/to/libryml.a path/to/libc4core.a"
tar cf - $libs | ( cd ${INSTALL_PFX}/lib ; tar xfp - )

# hdrs
hdrs=$(cd rapidyaml/src ; find . * -name '*.hpp' -o -name '*-.h') // every ryml header
# install to the destination include folder
( cd rapidyaml/src ; tar cvf - $hdrs $c4core $ext | ( cd ${INSTALL_PFX}/include ; tar xfp - ) )

# c4core hdrs and deps
c4core=$(cd rapidyaml/extern/c4core/src ; find  -name '*.hpp')
( cd rapidyaml/extern/c4core/src ; tar cvf - $c4core | ( cd ${INSTALL_PFX}/include ; tar xfp - ) )
# these ones need to be on the global include path for now (but the cmake install target will fix that)
ext="rapidyaml/extern/c4core/extern/sg14/inplace_function.h rapidyaml/extern/c4core/extern/debugbreak/debugbreak.h"
cp -vf $ext ${INSTALL_PFX}/include
```

FWIW, I've already started work on adding cmake install targets to these projects; that will make it much easier to install than doing the full song and dance with the procedure above. I'm hoping that feature will be added within the coming weeks. So maybe you could hold on this until that feature comes. I'll notify you here when it's done.

But please note that the recommended way to link with ryml is adding it as a subdirectory of your cmake project. That way you don't have to worry about version compatibility, compile flags or system updates; ryml will use the exact same compiler settings of your project. See the [c4core README.md](https://github.com/biojppm/c4core/blob/master/README.md) for an example on how to do that.

**Comment by biojppm** [comment]
@jbosboom Recently implemented install of the library. By default, c4core is now incorporated into ryml (you can control that with `cmake -D RYML_STANDALONE=ON/OFF`, which defaults to ON).

For now that should suffice to make it easier to create the pack . Later on, I will use cpack to set this up automatically (but no immediate plans for that).
