### ISSUE TITLE
Checking if a value is a float

### ISSUE THREAD

**Issue by Seally** [biojppm/rapidyaml#184]
I'm trying to check if a certain node contains a value convertible to a float. I'm currently trying something like:

```cpp
ryml::NodeRef valueNode; // assume value node is initialized elsewhere.
float defaultValue = 300;
float myFloat = 0;
auto isParseSuccessful = ryml::atof(valueNode.val(), &myFloat);

if (!isParseSuccessful) { myFloat = defaultValue; }
```

or simply just `valueNode >> myFloat;` but apparently `ryml::atof()` has the assertion `C4_ASSERT(str == str.first_real_span())` so it throws whenever a value is something like `"infinity"` (it looks like `fast_float` itself interprets any input that starts with `"inf"` as infinity). 

I tried commenting out the assert and it seems to work, though that's hardly ideal. I can also just parse the string directly with `fast_float` (or with methods), though that also feels wrong when the signature of the `atof` function suggests that it should just return false on error.

The quickstart doesn't seem to suggest any other obvious ways of reading these values, so I would appreciate some pointers to see if I'm missing something in the docs (technically this can also be a `c4core` issue and probably affects other similar functions as well).

**Comment by biojppm** [comment]
It seems you forgot the code? Anyway, you have csubstr.is_real().

**Comment by Seally** [comment]
Ah, thanks. I somehow didn't think to check the csubstr properties.

**Comment by biojppm** [comment]
Wait; let's not close this yet. If this is an infinity use case, it is relevant and it should be clear.

In YAML infinity should be encoded as `.inf`. There is a function `from_chars_float()` that handles this, and `NodeRef::operator>>()` uses this function. So if you use `.inf` for your value, it should just work without any special code. The quickstart  sample has example code for this in `sample_fundamental_types()`.

Or is it something else?

**Comment by biojppm** [comment]
@Seally PR #186 added successful parsing of `infinity` as well. The assert in `atof()` was too stringent, and incompatible with the corresponding asserts in `atoi()` and `atou()`. All the corresponding methods in `csubstr` were adjusted to account for this.
