### ISSUE TITLE
YAML Test Suite event output

### ISSUE THREAD

**Issue by perlpunk** [biojppm/rapidyaml#194]
Hi,

I'm trying to integrate rapidyaml into https://matrix.yaml.info/ (and for that I need it in [yaml-runtimes](https://github.com/yaml/yaml-runtimes))

For that I need to write a program that outputs events in the test suite format (example: https://github.com/yaml/yaml-test-suite/tree/data-2022-01-17/229Q)

So for libyaml you can try the following:
```
echo 'foo: bar' | docker run -i --rm yamlio/alpine-runtime-static c-libyaml-event
+STR
+DOC
+MAP
=VAL :foo
=VAL :bar
-MAP
-DOC
-STR
```
I see that ryml uses the test suite, but I haven't found where the events are created. Is it correct that it creates a tree and then walks through it to compare to the test suite events?
Would it be possible to write a program like the above? I looked at test_suite.cpp, but my C++ knowledge is very limited.

edit: [example for yaml-cpp in yaml-runtimes](https://github.com/yaml/yaml-runtimes/blob/master/docker/static/utils/yaml-cpp-event.cpp)

**Comment by biojppm** [comment]
Hi @perlpunk - thanks for looking at this! And further thanks for your work in the test suite and in the library, they have been invaluable to me.

I was going to get to this in the coming weeks, and I intended to submitting a PR to https://github.com/yaml/yaml-test-suite/ . So it's nice that you have started!

At the moment I am not sure how to do it. FWIW, in my internal tests looking at the test suite, I am reading the event sequence, [building a ryml tree out of it](https://github.com/biojppm/rapidyaml/blob/master/test/test_suite/test_suite_events.cpp) (ie, build the expected tree) and comparing with the actual tree obtained from parsing directly the yaml/json/emit/etc chunks.

Do I understand correctly that the test suite expects it the other way around? Ie, that it wants an executable from  the tested library to consume YAML from stdin (or is it from file?) and emit the event sequence from the parsed tree? If so, then there is nothing yet - I was approaching it from the opposite perspective. Ha.

But looking at the yaml-cpp link you provided, writing the program for that is definitely doable, and not too much trouble. I'll try to kick off things soon.

**Comment by perlpunk** [comment]
Yeah, I looked into the code under `test/test_suite` a bit.
For using the test suite on your side it doesn't matter in which way you are approaching it.

We as the test creators/maintainers like to play with the several libraries, and for that it's nice to have programs that output the same event format, and for creating the Test Matrix I also need it.
Two tools to play with the libraries you can see in the matrix:
* https://play.yaml.io/main/parser
* https://github.com/yaml/yaml-runtimes + https://github.com/yaml/yaml-editor

> But looking at the yaml-cpp link you provided, writing the program for that is definitely doable, and not too much trouble. I'll try to kick off things soon.

Cool, looking forward to it.

@pantoniou mentioned your lib in our chat, so I started looking at it.
Stop by if you like: https://matrix.to/#/#chat:yaml.io

**Comment by biojppm** [comment]
> edit: btw, so far all the yaml-runtimes libraries are using alpine based docker images, but I haven't tried to build ryml on alpine yet, only ubuntu. Hopefully it will also build on alpine, otherwise I have to put it into a seperate image.

Never used alpine, can't really tell. If it has cmake>=3.13 and a c++11 compiler and the standard library it should definitely build. I don't expect any failures, but if anything does fail, can you open an issue? I'd be happy to address those with celerity.

**Comment by biojppm** [comment]
@perlpunk I added an initial version of the event producer at #196. It is still far from complete, and I have a number of questions regarding what is or is not required there.

By far the biggest question is whether the events need to be exact, or if only the semantic result is of importance. For example, in the original YAML a scalar may be given as block folded, in which case the corresponding filtering will be applied while parsing; the filtered scalar will then be stored into ryml's tree, and marked quoted. Then when emitting the test suite events, ryml has no way to tell whether the scalar was originally block-folded, block-literal, single-quoted or double-quoted in the source YAML - only that it was one of these. So it is emitting only single-quoted scalars, or unquoted scalars. The content of the scalar in the event stream emitted by ryml's tool will be correct vis-a-vis its form, but depending on how you view it, the scalar form spec may or may not be correct.

If it is the case that the scalar needs to be presented in the event stream in the exact same form of the YAML source, then integration into the YAML test suite needs to wait for my ongoing work in style preservation/control at #191 which will enable this. Otherwise, with some adjustments to the tool we can proceed.

One thing that is missing is `=ALI`, will add it shortly. There are other questions; I've noted them in the [code for the tool](https://github.com/biojppm/rapidyaml/blob/07c3ab59cd7bd1a1099d36ef08bea32a253b8b9c/tools/yaml_events.cpp). As it is, if I use the code with for example the case file spec `35KP`:
```console
./ryml-yaml-events yaml-test-suite/src/src/35KP.yaml
+STR
 +DOC ---
  +SEQ
   +MAP
    =VAL :name
    =VAL :Tags for Root Objects
    =VAL :from
    =VAL :NimYAML tests
    =VAL :tags
    =VAL :explicit-key header mapping tag
    =VAL :yaml
    =VAL '--- !!map\n? a\n: b\n--- !!seq\n- !!str c\n--- !!str\nd\ne\n
    =VAL :tree
    =VAL '+STR\n +DOC ---\n  +MAP <tag:yaml.org,2002:map>\n   =VAL :a\n   =VAL :b\n  -MAP\n -DOC\n +DOC ---\n  +SEQ <tag:yaml.org,2002:seq>\n   =VAL <tag:yaml.org,2002:str> :c\n  -SEQ\n -DOC\n +DOC ---\n  =VAL <tag:yaml.org,2002:str> :d e\n -DOC\n-STR\n
    =VAL :json
    =VAL '{\n  "a": "b"\n}\n[\n  "c"\n]\n"d e"\n
    =VAL :dump
    =VAL '--- !!map\na: b\n--- !!seq\n- !!str c\n--- !!str d e\n
   -MAP
  -SEQ
 -DOC
-STR
```
Again, notice that the multiline scalars are all using `=VAL '...` instead of `=VAL |...`.

**Comment by perlpunk** [comment]
ok, let's go through it :)

## How to find out the required event output for the tool

The easiest way on the commandline, if you have docker, is to use
```
echo 'foo: bar' | docker run -i --rm yamlio/alpine-runtime-static c-libfyaml-event
```
The image is really small.
libfyaml currently passes all testsuite cases.

If you don't have docker, then I recommend to install [libfyaml](https://github.com/pantoniou/libfyaml) and run
```
echo 'foo: bar' | fy-tool --testsuite -
```
Or in a browser, use https://play.yaml.io/main/parser and look at the output of the "New Reference Parser (JS)" on the left side.

As you can see, the output from this tool should not be indented.

## What's required and what's optional?

Just use as many information you can get from the parsing process. YAML does not require parsers to keep all this information; in fact it explicitly says that some information should be thrown away, but looking at what YAML libraries are used for today, it can be really useful to keep this information for roundtripping.

Several libraries don't output certain things, and I deal with that in the Test Matrix:
* No alias/anchor names, so some output only `&id001` or `&1`
* No scalar style, in that case it's best to just output `:`. If you can distinguish between quoted and unquoted, then using `:` and `'` sounds like the best option, and I will deal with it in the test matrix.
* No information about explicit document start `---` or end `...`
* No indicator if the sequence or mapping is in flow style (`+MAP {}`, `+SEQ []`)

## Using the test suite in your tests

The easiest way is to use the data releases for testing.
It's documented in the README.
If you use the source files in the main branch directly, you might have to much work in transforming certain characters.

Again, if you don't keep all the information which you can see in the test.event files, just compare the information you have.

You can always ask us more question in the chat I mentioned above, or if you're an IRC person, some of us are also in the libera#yaml channel :)
Or open an issue in yaml-test-suite

**Comment by biojppm** [comment]
Thanks for all the info, it is definitely useful and directly answers many questions.

**Comment by biojppm** [comment]
Hi @perlpunk ! I've finally added the event emission tool. It is also now running successfully as part of my test suite, meaning that the events emitted from the trees I parse from the yaml-test-suite yaml/json/emit/dump parts allow me to create a tree which is exactly the same as the one I am parsing from the yaml-test-suite events. (phew!, sounds complicated but the idea is simple)

This is of course excluding the yaml-test-suite cases [which I am explicitly skipping](https://github.com/biojppm/rapidyaml/blob/master/test/test_suite/test_suite_parts.cpp). Some of those I plan to fix, but many of them not. 

Now I will try to kick things with a PR to the yaml runtimes. See you there! And of course, feel free to reopen this (or add new issues) if anything is not right. Thanks!
