### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by parihaaraka** [biojppm/rapidyaml#197]
tried to upgrade:
```
CMake Error at third_party/rapidyaml/ext/c4core/CMakeLists.txt:78 (add_custom_target):
  BYPRODUCTS path

    /home/me/projects/test/third_party/rapidyaml/ext/c4core/src_singleheader/c4/c4core_all.hpp

  in a source directory as an output of custom command.
```

**Comment by biojppm** [comment]
Thanks for reporting. What is the cmake version? And what is the ryml version?

**Comment by parihaaraka** [comment]
add_subdirectory(third_party/rapidyaml)
cmake version 3.22.1
clean ryml clone (recursive) of the latest commit

**Comment by parihaaraka** [comment]
i beg your pardon, this is due to
`set(CMAKE_DISABLE_SOURCE_CHANGES  ON)`
