### ISSUE TITLE
In situ parsing

### ISSUE THREAD

**Issue by sherief** [biojppm/rapidyaml#2]
Is parsing a YAML buffer in-situ a use case you plan to support? rapidJSON has that feature and it's great from a performance standpoint.

**Comment by biojppm** [comment]
Absolutely. This is a central tenet of ryml. The buffer needs to be writable though (this is necessary because YAML literal blocks need to have their indentation removed in-place).

Note that the ryml tree will not take ownership of the YAML source buffer, so do not let it run out of scope while the tree is in use.

```
int main()
{
    std::vector<char> srcbuf; // = "{foo: 1}"
    ryml::span src(srcbuf.data(), srcbuf.size()); // a writeable string view

    auto tree = ryml::parse(src);
    auto root = t.rootref();

    int foo;
    root["foo"] >> foo;
}
```

**Comment by sherief** [comment]
So is all parsing in-situ? If so I think it should be an option since I won't be able to use it with memory-mapped files for example.

**Comment by biojppm** [comment]
Yes, all parsing is in situ, and after parsing the tree nodes are pointing at the source buffer spans.

Initially, I had the source buffer as a const char* (actually a ryml::cspan), but YAML literal blocks needed to have the indentation characters removed, so I opted to do it in-place in the source buffer to save allocations. Conceivably, the tree can use an alternative const span and write to its arena.

But is this really needed? If the source can't be written to, why not copy it to a different buffer before parsing and then treat that copy as the source to be parsed?

**Comment by sherief** [comment]
Fair enough. Closing.

**Comment by biojppm** [comment]
I am reconsidering your position of passing const strings to the ryml parser. The cost shouldn't be too 
much:
- some branches starting the parse and during filtering escaped and indentation characters in blocks/quoted scalars).
- allocations from the arena for the filtered scalars/blocks (this is of course on a need basis)

 OTOH the copy IS expensive for everyone with a const buffer. So this request certainly has merit. If you or anyone reading this would like to pass in a const buffer without copying it, reopen this issue.

**Comment by sherief** [comment]
Yes please, parsing const strings would be great - seen the malloc() / memcpy() song and dance I had to do when I provided a sample for issue #3?

**Comment by biojppm** [comment]
Well, I did! But there are easier ways to do it!
