### ISSUE TITLE
Issues with new event formatter

### ISSUE THREAD

**Issue by ingydotnet** [biojppm/rapidyaml#200]
I realize https://github.com/biojppm/rapidyaml/commits/master/tools/yaml_events.cpp is brand new and still a work in progress, but I was able to integrate it into our parser playground https://play.yaml.io/main/parser and run our yaml-test-suite against it. It's failing 283/402 tests and I thought I'd share the low hanging fruit cases here.

* https://play.yaml.io/main/parser?input=Zm9vOiBAYmFyCg==
  * It seems to never error on invalid yaml. The new program should should exit with non-zero in such cases.

* https://play.yaml.io/main/parser?input=Zm9vOiBiYXIK works
  * https://play.yaml.io/main/parser?input=Zm9vOiBiYXIKLi4uCg== fails for not `-DOC ...`
  * https://play.yaml.io/main/parser?input=LS0tCmZvbzogYmFyCg== fails for `-DOC ...` when it should not

* https://play.yaml.io/main/parser?input=LSAiZm9vIgo= shows double quoted as single quoted

* https://play.yaml.io/main/parser?input=LSAhIXN0ciBmb28K
  * I know rapid yaml doesn't expand tags but you could expand `!!foo` to `<tag:yaml.org,2002:foo>` in the events tool.

* https://play.yaml.io/main/parser?input=LSB8Cg==
  * Empty block scalars crash the program

* https://play.yaml.io/main/parser?input=LSB8CiAgZm9vCg==
  * Block scalars should report `|foo\n` and `>foo\n`. Similar issue to double quoting above.

* https://play.yaml.io/main/parser?input=JngKLSAqeAo=

That's a start for you.

**Comment by perlpunk** [comment]
@ingydotnet we discussed some of these things already in #194

**Comment by biojppm** [comment]
Thanks for all the notes @ingydotnet . 

From the outset I need to make it clear that ryml will definitely not be able to pass the full suite.

Notably, it does not flag errors in many of the expected cases (this requires fixing, but I won't be able to look at this any time soon). And -- deliberately -- there is no support for container keys; keys need to be scalars. There are others; I've noted them all down [in this file](https://github.com/biojppm/rapidyaml/blob/master/test/test_suite/test_suite_parts.cpp), which guides the skipping of the test-suite case parts in my CI.

Other than the cases noted in the file linked above, ryml is expected to succeed in every test case, in any of its parts, as demonstrated by the fact that all non-skipped test parts succeed in the CI.

**Comment by ingydotnet** [comment]
I realize that you don't intend to pass the suite. This report was just to improve the new tool you made to easily pass a lot more than it currently does. iow tests that likely fail due to the new test program rather than rapidyaml.

Although some of the things I pointed out do cause rapidyaml to dump core.

Here is a compilation of all the current tests containing valid YAML that rapidyaml fails:
https://gist.github.com/ingydotnet/8aabea3e0cf965564dbb8c5d278c38cb
221 or the 283 (the others are error tests).

It looks like https://github.com/biojppm/rapidyaml/blob/master/test/test_suite/test_suite_parts.cpp is a bit dated. We've been adding many new tests. Some of them are mullti-tests with ids like `3RLN-03`.

**Comment by ingydotnet** [comment]
2G84-02 https://play.yaml.io/main/parser?input=LS0tIHwxLQ==
is one of the new tests that crashes rapidyaml, fyi.

**Comment by biojppm** [comment]
Wow, many more tests indeed. I updated the yaml-test-suite to the current tip I and I have 48 new failures, mostly aborts:
```console

The following tests FAILED:
	122 - ryml-test-suite-2G84-in_yaml-errors (Failed)
	713 - ryml-test-suite-6CA3-in_yaml (Subprocess aborted)
	714 - ryml-test-suite-6CA3-in_yaml-events (Subprocess aborted)
	715 - ryml-test-suite-6CA3-in_yaml-emit_events (Subprocess aborted)
	720 - ryml-test-suite-6CA3-emit_yaml (Failed)
	721 - ryml-test-suite-6CA3-emit_yaml-events (Failed)
	722 - ryml-test-suite-6CA3-emit_yaml-emit_events (Failed)
	1898 - ryml-test-suite-DK95-emit_yaml-events (Failed)
	1899 - ryml-test-suite-DK95-emit_yaml-emit_events (Failed)
	2375 - ryml-test-suite-JEF9-in_yaml-events (Failed)
	2376 - ryml-test-suite-JEF9-in_yaml-emit_events (Failed)
	2379 - ryml-test-suite-JEF9-out_yaml-events (Failed)
	2380 - ryml-test-suite-JEF9-out_yaml-emit_events (Failed)
	2580 - ryml-test-suite-L24T-emit_yaml-events (Failed)
	2581 - ryml-test-suite-L24T-emit_yaml-emit_events (Failed)
	2682 - ryml-test-suite-M2N8-in_yaml (Subprocess aborted)
	2683 - ryml-test-suite-M2N8-in_yaml-events (Subprocess aborted)
	2684 - ryml-test-suite-M2N8-in_yaml-emit_events (Subprocess aborted)
	2686 - ryml-test-suite-M2N8-out_yaml (Subprocess aborted)
	2687 - ryml-test-suite-M2N8-out_yaml-events (Subprocess aborted)
	2688 - ryml-test-suite-M2N8-out_yaml-emit_events (Subprocess aborted)
	2770 - ryml-test-suite-MUS6-in_yaml (Subprocess aborted)
	2771 - ryml-test-suite-MUS6-in_yaml-events (Subprocess aborted)
	2772 - ryml-test-suite-MUS6-in_yaml-emit_events (Subprocess aborted)
	2773 - ryml-test-suite-MUS6-in_yaml-errors (Subprocess aborted)
	2774 - ryml-test-suite-MUS6-out_yaml (Subprocess aborted)
	2775 - ryml-test-suite-MUS6-out_yaml-events (Subprocess aborted)
	2776 - ryml-test-suite-MUS6-out_yaml-emit_events (Subprocess aborted)
	2777 - ryml-test-suite-MUS6-emit_yaml (Subprocess aborted)
	2778 - ryml-test-suite-MUS6-emit_yaml-events (Subprocess aborted)
	2779 - ryml-test-suite-MUS6-emit_yaml-emit_events (Subprocess aborted)
	2780 - ryml-test-suite-MUS6-in_json (Subprocess aborted)
	3551 - ryml-test-suite-UKK6-in_yaml (Subprocess aborted)
	3552 - ryml-test-suite-UKK6-in_yaml-events (Subprocess aborted)
	3553 - ryml-test-suite-UKK6-in_yaml-emit_events (Subprocess aborted)
	3752 - ryml-test-suite-Y79Y-in_yaml-errors (Failed)
	3774 - ryml-test-suite-YJV2-in_yaml-errors (Failed)
	3892 - ryml-test-suite-ZYU8-in_yaml (Subprocess aborted)
	3893 - ryml-test-suite-ZYU8-in_yaml-events (Subprocess aborted)
	3894 - ryml-test-suite-ZYU8-in_yaml-emit_events (Subprocess aborted)
	3895 - ryml-test-suite-ZYU8-in_yaml-errors (Subprocess aborted)
	3896 - ryml-test-suite-ZYU8-out_yaml (Subprocess aborted)
	3897 - ryml-test-suite-ZYU8-out_yaml-events (Subprocess aborted)
	3898 - ryml-test-suite-ZYU8-out_yaml-emit_events (Subprocess aborted)
	3899 - ryml-test-suite-ZYU8-emit_yaml (Subprocess aborted)
	3900 - ryml-test-suite-ZYU8-emit_yaml-events (Subprocess aborted)
	3901 - ryml-test-suite-ZYU8-emit_yaml-emit_events (Subprocess aborted)
	3902 - ryml-test-suite-ZYU8-in_json (Subprocess aborted)
```

**Comment by biojppm** [comment]
I've checked the failures, and it's from around 10 cases, mostly patological in ryml terms. I've added exclusions to the parts in the commit linked above.

**Comment by ingydotnet** [comment]
Note, you should probably change the IDs for the multi-tests.

`ZYU8-00` - `ZYU8-03`
`Y79Y-000` - `Y79Y-010`
etc

See also: https://github.com/yaml/yaml-test-suite/tree/data

Also note that ZYU8 is marked skip. You can skip those altogether.

**Comment by biojppm** [comment]
> Note, you should probably change the IDs for the multi-tests.

Indeed! I will have to rewrite the infrastructure to discover the test cases not from the test suite src folder but from the data directories. As an upside, it will simplify my code as well. But unfortunately I cannot do it ATM....

> Also note that ZYU8 is marked skip. You can skip those altogether.

Yes, thanks for the note. I'm doing that already based on the `skip` directive, but the particular problem with ZYU8 was that my parser for the test suite case file did not like some of the new directives in there. Again, if I rewrite the discoverability logic to use the `data` folder I will not have to deal with this situation anymore.

**Comment by biojppm** [comment]
@ingydotnet @perlpunk I'm trying to find a way to run the tests from the test-suite infrastructure using the command line, but I am a bit confused with the multiple repos, docker images and organization. Also it's my first time using docker, which may be making it even worse. Can you give me some guidance on this?
  * What is the project to use to accomplish running in the command line all the tests with a particular library?
  * And is there a command I can use to run a single test by ID?
  * I'm trying to do a `make static` in `ryml-runtimes`, but I'm getting this error (despite being logged in to docker):
  ```console
   ...
   Building cpp-rapidyaml
   cpp-rapidyaml
   rapidyaml-0.3.0-src.tgz exists, skip
   Building cpp-rapidyaml...
   # docker run -it --rm --user 1000 --env HOME=/tmp/home --env VERSION=0.3.0 --env SOURCE=/sources/rapidyaml-0.3.0-src.tgz --env LIBNAME=cpp-rapidyaml -v/home/jpmag/proj/yaml-runtimes/bin/../docker/static/utils:/buildutils -v/home/jpmag/proj/yaml-runtimes/bin/../var/source/static:/sources -v/home/jpmag/proj/yaml-runtimes/bin/../var/build/static:/build yamlio/alpine-builder-static /buildutils/cpp-rapidyaml-build.sh
   Unable to find image 'yamlio/alpine-builder-static:latest' locally
   docker: Error response from daemon: pull access denied for yamlio/alpine-builder-static, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
   See 'docker run --help'.
  ```
 To be clear, this error happens for every library in the `static` image. `docker image list` shows me this:
  ```console
  $ docker image list
  REPOSITORY                          TAG          IMAGE ID       CREATED          SIZE
  yamlio/alpine-runtime-static        latest       bcfc30b04034   26 minutes ago   10.6MB
  ...
  ```
  I'm sorry if this is just my docker f*ckup, but I'm having trouble getting out of this hole.
  * The links for the excel spreadsheet you have been giving me are all empty for me, except for the header row. Is something off in my end?

**Comment by biojppm** [comment]
On the upside I was able to successfully `make build` and `make test` in yaml-test-runtimes.

**Comment by perlpunk** [comment]
Regarding `make static` in yaml-runtimes - this should create a `alpine-builder-static` image and build all the c/c++/... libraries in it, and then create `alpine-runtime-static`.
If it tries to fetch the builder image from docker, there's something wrong, and the builder images are not on dockerhub.
I would try `make clean` and run it again.
This is for building all the libraries.

The runtime images are all pushed to dockerhub, so people can play with the libraries without building themselves.

**Comment by perlpunk** [comment]
> What is the project to use to accomplish running in the command line all the tests with a particular library?

It depends a bit what exactly you want to do.
The yaml-runtimes images contain the latest official releases.
yaml-test-matrix uses these images to run all the tests. It creates data files with all test output and the matrix HTML page.
You should be able to do:
```
cd yaml-test-matrix
make build
```
But note that this can take a while, as it runs 43 views (event, json & native data (if supported) output for every library). Takes about 20 minutes here currently.
If you want to just generate it for one library, you can manually execute the commands in the Makefile, and replace
```
        ./bin/run-framework-tests --all
        ./bin/compare-framework-tests --all
```
with
```
        ./bin/run-framework-tests -f cpp-rapidyaml.event
        ./bin/compare-framework-tests -f cpp-rapidyaml.event
```
Then you should get HTML pages under `matrix/html/`, and the pure data under `matrix/data/`.
So far only one person has ever asked how to run it, and I might have forgotten things while just running it on my machine only, so let me know if this doesn't work.
Of course for this rapidyaml needs to be in alpine-runtimes-static already.

**Comment by biojppm** [comment]
Success with yaml-runtimes! I was able to `make static`; it was the `make clean` that fixed it. Thanks!
