### ISSUE TITLE
URL to yaml-test-suite is invalid

### ISSUE THREAD

**Issue by ingydotnet** [biojppm/rapidyaml#201]
https://github.com/biojppm/rapidyaml/blob/ec5e971af91c914cbe4f7d486dacae70a98b0b04/test/test_suite/test_suite_parts.cpp#L20

Changed from `…/test/` to `…/src/`.

**Comment by biojppm** [comment]
Ha, thanks for reporting!

**Comment by ingydotnet** [comment]
FYI. A bunch of new tests have been added in past months.
