### ISSUE TITLE
error in README example

### ISSUE THREAD

**Issue by cburgard** [biojppm/rapidyaml#21]
The example tree emission in the README doesn't currently work (error message attached). The offending line is
`    std::string tmp = "child5";
    s.append_child() << tmp;`

It boils down to a missing `to_chars` for `std::string`. Possible to circumvent by using 
`    std::string tmp = "child5";
    s.append_child() << tmp.c_str();`
in the example, but not very nice. Tested with gcc 6.2.0.
[error.txt](https://github.com/biojppm/rapidyaml/files/3922183/error.txt)

**Comment by biojppm** [comment]
Thanks for the catch. Will fix.

**Comment by biojppm** [comment]
FYI, this works as-is. I clarified the README.md in the linked commit.

But you do need to add the right include; in this case [`#include <c4/yml/std/string.hpp>`](https://github.com/biojppm/rapidyaml/blob/master/src/c4/yml/std/string.hpp) (which for now is just a convenience header bringing in the c4core header [`#include <c4/std/string.hpp>`](https://github.com/biojppm/c4core/blob/master/src/c4/std/string.hpp).

This is actually covered in the [basic test](https://github.com/biojppm/rapidyaml/blob/af0124bbddfdf35998bbe24131d4fc6a16dd0157/test/basic.cpp#L1266) which is run in the CI.
