### ISSUE TITLE
Readme contains dead link to changelog

### ISSUE THREAD

**Issue by Gei0r** [biojppm/rapidyaml#219]
I just wanted to upgrade rapidyaml and to see what changed in the meantime, I wanted to look at the changelog, but the link in the readme ([https://github.com/biojppm/rapidyaml/changelog](https://github.com/biojppm/rapidyaml/changelog)) is a dead link!

Maybe just writing the link as `[the changelog](changelog)` might work in the readme as a relative link to the directory, but I'm not sure. From the issue it doesn't work.

**Comment by biojppm** [comment]
Thanks for reporting!

**Comment by Gei0r** [comment]
Another small thing (don't want to open a new issue): The link to RISC-V is broken (wrong closing bracket)
