### ISSUE TITLE
Per-phase callbacks

### ISSUE THREAD

**Issue by biojppm** [biojppm/rapidyaml#222]
> error handling callbacks are shared for the entire lib, and don't have much info about where the error came from (parent ref, parser-error vs data-extraction error) so we can't really play with this mechanism (enabling errors on parse and disabling on data-extraction is a no go on multi-threaded apps), we've decided to throw on error (abort in a server app when user sends corrupted data is not a good solution), that would be awesome improve this giving more flexibility.

@fargies 
You definitely can have per-tree callbacks, different from the global library-scope callbacks. Further, you can also have per-phase callbacks (ie parsing vs data-extraction), by instantiating (prior to parsing) a parser and a tree with different callbacks, and then providing the existing tree to the appropriate method in the existing parser. This second aspect I've not explored much, so if something is not working as I described, then that's definitely a rapidyaml bug which should be addressed; further, if there are indeed problems, they will be very easy to fix by simply ensuring the proper callbacks object is used in the parser code (the data-extraction logic happens in the tree/noderef and is by definition calling into the right callbacks object).

HTH.

_Originally posted by @biojppm in https://github.com/biojppm/c4core/issues/75#issuecomment-1055423130_

**Comment by biojppm** [comment]
@fargies I opened a bug here to track this question as it is important to get right. There is [an example in the quickstart](https://github.com/biojppm/rapidyaml/blob/ed547aa008f1d891a28491788a6a855959414269/samples/quickstart.cpp#L3680) which shows how to have per-tree callbacks. The example is focused on allocation rather than error handling but the logic is exactly the same since both are handled in the callbacks structure.

That example should help you get there; there are also tests covering this scenario. And if something is off, do let me know here so that it can be added to the tests and fixed.

**Comment by fargies** [comment]
Thanks for the hint :+1: I'll start using it and dig into it.

**Comment by biojppm** [comment]
Did this work for you?

**Comment by fargies** [comment]
In the end I kept on using global hooks and added some small helpers functions to handle data-extractions errors, mainly `get(node, ...)` and `default_to`, which gives code like this:

```cpp
yml::get(root, "foo", "bar", 1, "baz") >> yml::default_to(value, 12);
```

This is a bit inspired from [lodash](https://lodash.com/docs/4.17.15#get) and [json-pointer](https://datatracker.ietf.org/doc/html/rfc6901).
It may need to maturate a bit, but I can share it if you wish.

Thanks for caring :)

**Comment by biojppm** [comment]
ok, closing now. Feel free to reopen if something's not right with the callback mechanism.
