### ISSUE TITLE
Parsing key with leading colon

### ISSUE THREAD

**Issue by sconde** [biojppm/rapidyaml#233]
I'm attempting to replace `yaml-cpp` with rapidyaml in my project. 

An example document is like 
```
:foo:
  :bar: a
  :barbar: b
  :barbarbar: c
```

Although `yaml-cpp` is able to parse with the leading colon character, rapidyaml is unable to handle this
```
1:1:ERROR: parse error
1:1: :foo:  (size=5)
     ^~~~~  (cols 1-6)
```

**Comment by biojppm** [comment]
thanks for reporting

**Comment by biojppm** [comment]
While waiting for a fix, ensuring these keys are quoted will [enable rapidyaml to parse this](https://play.yaml.io/main/parser?input=Jzpmb28nOgogICc6YmFyJzogYQogICc6YmFyYmFyJzogYgogICc6YmFyYmFyYmFyJzogYw==)
