### ISSUE TITLE
Endless loop when using error callback

### ISSUE THREAD

**Issue by Beliaar** [biojppm/rapidyaml#235]
For testing error handling I have given rapidyaml the string ":--" to parse. While the callback itself works it is called repeatedly resulting in an endless loop.

The following code reproduces the error:

```
#include <iostream>
#include "ryml.hpp"

void on_error(const char *msg, size_t len, ryml::Location loc, void *_) {
    auto message_string = std::string(msg, len);
    auto name_string = std::string(loc.name.str, loc.name.len);
    std::cout << "Error parsing yaml: " << name_string << "(" << loc.line + 1 << ", " << loc.col + 1 << ") ("
                 << loc.offset << "): " << message_string;
}

int main() {
    ryml::Callbacks callbacks;
    callbacks.m_error = on_error;
    ::ryml::set_callbacks(callbacks);
    char yml_buf[] = ":--";
    auto tree = ::ryml::parse_in_place("", ryml::substr(yml_buf));
    return 0;
}

```

**Comment by Beliaar** [comment]
Okay, I just saw that it is intended. I will see if I can somehow abort the call from the handler, but I don't think so.

I think there should be some way from the handler to cause the parser to just stop.

**Comment by biojppm** [comment]
The handler must not return control to the caller. It must either raise an exception, jump elsewhere or abort.

**Comment by biojppm** [comment]
To clarify: this is done this way because there is nothing that can be done on the parser side to allow continuing after a parse error occurs. It must be stopped or run the risk of crashing.

**Comment by Beliaar** [comment]
Okay, I will find something on my side, then.
