### ISSUE TITLE
Request: Publish Doxygen API docs

### ISSUE THREAD

**Issue by mcandre** [biojppm/rapidyaml#238]
Hi,

Can we please get more formal API docs published for this package? The existing documentation talks about the project at a high level, but neglects to go into member by member detail, as we would find in a standard API document.

It's not even clear to a novice like me which rapidyaml header paths I should include in my downstream code.

We can quickly write and generate conventional API documentation with Doxygen.

https://www.doxygen.nl/index.html

Example project with Doxygen documentation: https://github.com/mcandre/swiper

**Comment by jzakrzewski** [comment]
second that!

**Comment by biojppm** [comment]
Resolved in #423
