### ISSUE TITLE
Benchmark: KeyVal node

### ISSUE THREAD

**Issue by captain-yoshi** [biojppm/rapidyaml#242]
Comming from yaml-cpp, my first intuition was to write KeyVal nodes like `Version A`. But in the examples, I see that `Version B` is used. So I decided to benchmark the 2 versions and against yaml-cpp. Are there any reason to use `append_child()` when storing KeyVal pairs ? It seems slower and less compact... I imagine it could also speed up [std::map serialization](https://github.com/biojppm/rapidyaml/blob/master/src/c4/yml/std/map.hpp#L22-L24).

```cpp
// Version A
void write(c4::yml::NodeRef* n, collision_detection::CollisionRequest const& rhs)
{
    *n |= c4::yml::MAP;

    (*n)["distance"] << rhs.distance;
    (*n)["cost"] << rhs.cost;
    (*n)["contacts"] << rhs.contacts;
    (*n)["max_contacts"] << rhs.max_contacts;
    (*n)["max_contacts_per_pair"] << rhs.max_contacts_per_pair;
    (*n)["max_cost_sources"] << rhs.max_cost_sources;
    (*n)["verbose"] << rhs.verbose;
    (*n)["group_name"] << rhs.group_name;
}

// Version B
void write(c4::yml::NodeRef* n, collision_detection::CollisionRequest const& rhs)
{
    *n |= c4::yml::MAP;

    n->append_child() << yml::key("distance") << rhs.distance;
    n->append_child() << yml::key("cost") << rhs.cost;
    n->append_child() << yml::key("contacts") << rhs.contacts;
    n->append_child() << yml::key("max_contacts") << rhs.max_contacts;
    n->append_child() << yml::key("max_contacts_per_pair") << rhs.max_contacts_per_pair;
    n->append_child() << yml::key("max_cost_sources") << rhs.max_cost_sources;
    n->append_child() << yml::key("verbose") << rhs.verbose;
    n->append_child() << yml::key("group_name") << rhs.group_name;
}
```
### Benchmark

```cpp
std::vector<ryml::NodeRef> seq;
seq.reserve(1000);

double acc = 0;
for (std::size_t i = 0; i < 1000; ++i) {
    ryml::Tree t;
    ryml::NodeRef root = t.rootref();
    collision_detection::CollisionRequest req;

    start = std::chrono::high_resolution_clock::now();
    root << req;
    finish = std::chrono::high_resolution_clock::now();
    auto totaltime = std::chrono::duration_cast<std::chrono::duration<double>>(finish - start);

    acc += totaltime.count();
    seq.emplace_back(root);
}
```
Results with 8 keyval nodes.
| KeyVal = 8             | Time (s) / 1000 samples |
|------------------------|:-----------------------:|
| n['key']               |          0.0038         |
| append_child() + key() |          0.0053         |
| yaml-cpp               |          0.0755         |

Same as above but with 32 unique keyval nodes.
| KeyVal = 32            | Time (s) / 1000 samples |
|------------------------|:-----------------------:|
| n['key']               |          0.022          |
| append_child() + key() |          0.0295         |
| yaml-cpp               |          0.323          |

**Comment by biojppm** [comment]
Thanks for the results, they are interesting. The two alternatives are semantically similar, and should be more or less equivalent in cost. The 50% difference is surprising, and some profiling is required to find out why the difference is there. The `append_child()` approach is indeed more verbose, and (from the top of my head) 

BTW, is there a warmup factor at play here? Was this timing taken in different runs, or was it taken in a single run, sequentially? One quick thing to try would be to run the timing for each sample twice in succession, but only provide the second result - this ensures that the results are for a warm state, and thus improves comparability.

**Comment by captain-yoshi** [comment]
I was in Debug mode... You are right the two are similar once optimised. The benchmark above was the mean of cold 10 runs of 1000 trials without a warm-up factor. Redid the benchmark with warm-up factor and in Release mode!

| KeyVal = 32 + Warmup | Time (s) / 1000 samples |                        |                |
|----------------------|:-----------------------:|:----------------------:|----------------|
|                      | n['key']                | append_child() + key() | yaml-cpp       |
| Run 1                |        0.0019000        |       0.00202730       | 0.068359518    |
| Run 2                |         0.002031        |        0.0018832       | 0.06746137     |
| Run 3                |         0.002104        |        0.0018879       | 0.06826379     |
| Run 4                |         0.002066        |        0.0018980       | 0.06723345     |
| Run 5                |         0.001936        |        0.0018223       | 0.06854615999  |
| Run 6                |         0.002227        |        0.0018065       | 0.082099       |
| Run 7                |         0.001977        |        0.0018669       | 0.0673938      |
| Run 8                |         0.002032        |       0.00188117       | 0.06764831     |
| Run 9                |        0.0018555        |       0.00188685       | 0.06838606     |
| Run 10               |        0.00202508       |       0.001947568      | 0.067527660    |
| Mean                 |       0.002015358       |      0.0018907688      | 0.069291911799 |

**Comment by biojppm** [comment]
Ah, this makes more sense. The append_child approach is slighly faster because it doesn't do a lookup, I guess.

Also, it's nice to see the improvement over yaml-cpp.

Thanks for the data points.

**Comment by biojppm** [comment]
Is the performance important? I'm curious how much quicker the low-level index interface would be.
Eg (writing off the top of my head):

```c++
void write(c4::yml::NodeRef* n, collision_detection::CollisionRequest const& rhs)
{
    *n |= c4::yml::MAP;
    Tree *t = n->tree();
    size_t node = n->id();
    t->to_keyval(t->append_child(node), "distance", t->to_arena(rhs.distance));
    t->to_keyval(t->append_child(node), "cost", t->to_arena(rhs.cost));
    t->to_keyval(t->append_child(node), "contacts", t->to_arena(rhs.contacts));
    t->to_keyval(t->append_child(node), "max_contacts", t->to_arena(rhs.max_contacts));
    t->to_keyval(t->append_child(node), "max_contacts_per_pair", t->to_arena(rhs.max_contacts_per_pair));
    t->to_keyval(t->append_child(node), "max_cost_sources", t->to_arena(rhs.max_cost_sources));
    t->to_keyval(t->append_child(node), "verbose", t->to_arena(rhs.verbose));
    t->to_keyval(t->append_child(node), "group_name", t->to_arena(rhs.group_name));
}
```

**Comment by captain-yoshi** [comment]
Yes and no! My use case involves having multiple sequences of 10000 numbers from benchmarks. The other metadata are simple keyval. Using g++ by the way. I used `0` instead of the `node` variable.

Interesting, it seems that the `Tree API` is somewhat between 124% and 130% faster then the `Node API`. It goes up as the number of samples increases.

| Keyval = 32 + Warmup | Time (s) / 1000 samples |              |
|----------------------|-------------------------|--------------|
|                      | node API                | tree API     |
| 1                    | 0.001864038             | 0.001540474  |
| 2                    | 0.002158961             | 0.001557013  |
| 3                    | 0.002002845             | 0.001610177  |
| 4                    | 0.001883053             | 0.001635169  |
| 5                    | 0.002105777             | 0.001463451  |
| 6                    | 0.00186742              | 0.001555544  |
| 7                    | 0.001989846             | 0.001586058  |
| 8                    | 0.001952636             | 0.001634094  |
| 9                    | 0.001958484             | 0.001643127  |
| 10                   | 0.001825273             | 0.001490179  |
| mean                 | 0.0019608333            | 0.0015715286 |


----




| Keyval = 32 + Warmup | Time (s) / 10000 samples |              |
|----------------------|--------------------------|--------------|
|                      | node API                 | tree API     |
| 1                    | 0.019323439              | 0.014859541  |
| 2                    | 0.018879316              | 0.014429284  |
| 3                    | 0.019667321              | 0.014965601  |
| 4                    | 0.018960193              | 0.014472157  |
| 5                    | 0.01934724               | 0.014753694  |
| 6                    | 0.01939408               | 0.014417498  |
| 7                    | 0.019604276              | 0.014953592  |
| 8                    | 0.019276149              | 0.015080301  |
| 9                    | 0.019352651              | 0.01489798   |
| 10                   | 0.019020592              | 0.014554869  |
| mean                 | 0.0192825257             | 0.0147384517 |

**Comment by biojppm** [comment]
Nice. The node API builds on top of the index API and has a branch, whereas the index API has none. Also, less copying, so more speed. Thanks again for the data.

**Comment by captain-yoshi** [comment]
Thx again for your help and your amazing libraries!

Still have a way to go before converting my objects from yaml-cpp to ryml but here are my though so far:

- Better code verbosity
- So much customisation !
- Obviously speed!!!

I will post real world benchmarks once I fully finish converting to ryml.

**Comment by biojppm** [comment]
Great, thanks for the kind words. Just to add a note: when doing the benchmark timings, do the warmup+timing per approach, not per panel. Eg 

Approach1: warmup->timing
Approach2: warmup->timing
Approach3: warmup->timing

and not this:
warmup: Approach1->Approach2->Approach3
timing: Approach1->Approach2->Approach3

The reason is evident. In the latter way none of the approaches are warm when timed.

I'm not sure it is the case, but based on your tables above it seemed you were going for the latter way.
