### ISSUE TITLE
rapidyaml goes into infinite loop when parsing invalid YAML

### ISSUE THREAD

**Issue by linw789** [biojppm/rapidyaml#244]
With the code below, rapidyaml gets into an infinite loop. In [the sample code](https://github.com/biojppm/rapidyaml/blob/master/samples/quickstart.cpp#L3503), exception is used, which breaks the loop. But I can't use exception in my project. Is this a bug? Ca we break out of the infinite loop when error occurred?

```C++
#include <string.h>
#include <stdio.h>

#define RYML_SINGLE_HDR_DEFINE_NOW
#include "rapidyaml.h"

void error_handler(const char* msg, size_t len, ryml::Location loc, void* userdata)
{
    (void)loc;
    (void)userdata;
    printf("%.*s\n", len, msg);
}

int main(int argc, char** argv) {
    char* invalid_yaml = R"yaml(
Version: 2
Components:
  - Name:
  Values:
)yaml";

    ryml::set_callbacks(ryml::Callbacks(nullptr, nullptr, nullptr, error_handler));
    ryml::Tree tree = ryml::parse_in_place(ryml::substr(invalid_yaml, strlen(invalid_yaml)));
}
```

**Comment by biojppm** [comment]
The error handler must never return. It must either throw an exception or abort.

**Comment by biojppm** [comment]
Note that if you can't use exceptions or abort, [you can still use `longjmp()`](https://en.cppreference.com/w/cpp/utility/program/longjmp] to jump to a different execution context.

**Comment by linw789** [comment]
Unfortunately, I can't use `longjmp` either. Our code base is still on C++ 11.

**Comment by biojppm** [comment]
`longjmp()` is C, so you can definitely use it in any C++ standard.
