### ISSUE TITLE
New line symbol in windows

### ISSUE THREAD

**Issue by SauliusZ87** [biojppm/rapidyaml#252]
Is  there a way to change new line symbol for windows to '\r\n'.
Now when yaml is emitted, it is always saved with '\n'.
But windows by default uses \r\n

**Comment by biojppm** [comment]
No, there is nothing. The feature request is noted, however there are more pressing things to look at in the emitter, so don't expect this to appear anytime soon.

**Comment by biojppm** [comment]
As a workaround, please note that you can emit to buffer and subsequently replace `\n` with `\r\n` in the buffer, and then write the result to file.
