### ISSUE TITLE
Symbols ' and \\n fails to produce same output

### ISSUE THREAD

**Issue by SauliusZ87** [biojppm/rapidyaml#253]
Saved and loaded data is not the same in case symbols ' and \\n are used together

```
ryml::Tree tree;
ryml::NodeRef root = tree.rootref();
root |= ryml::MAP;
root["t"] = "t't\\nt";

std::string s = ryml::emitrs<std::string>(tree);

ryml::csubstr yml = ryml::csubstr(s.c_str(), s.size());
tree = ryml::parse_in_arena(yml);
root = tree.rootref();

auto s1 = root["t"].val();

const bool equal = s == s1;
```

**Comment by SauliusZ87** [comment]
Is there any workaround for this ?

**Comment by biojppm** [comment]
Sorry for the late reply. The original emitter is not escaping the backslash when using double quotes, which prevents the roundtrip equivalence. The new emitter can now be forced to pick a particular style, and has already been added but is still a work-in-progress. You can use it as a workaround:
```c++
ryml::Tree tree;
ryml::NodeRef root = tree.rootref();
root |= ryml::MAP;
root["t"] = "t't\\nt";
root["t"] |= _WIP_VAL_DQUO; // or _WIP_VAL_SQUO
```
but be aware that this may be subject to change in varying degrees.

**Comment by SauliusZ87** [comment]
One more string that fails to load properly, event with ryml::_WIP_VAL_DQUO.
When saved and then loaded, \r ir lost inside string. Loaded string becomes "t\nt" instead of "t\r\nt"
root["t"] = "t\r\nt";
