### ISSUE TITLE
amalgamate_utils.py missing

### ISSUE THREAD

**Issue by johannes90** [biojppm/rapidyaml#257]
Is it possible that the amalgamate_utils is missing? 

The amalgamate script is trying to import that. 
I tried to install/download it via console but could not find it and therefore thought it should be a local file
Is that true or am i missing something?

**Comment by biojppm** [comment]
Probably you did not checkout the git submodules while cloning. Ensure that happens by doing `git clone --recursive`.

**Comment by johannes90** [comment]
Thanks, that solved it. 
 Sorry for opening an issue, was totally my problem.
