### ISSUE TITLE
const on return types

### ISSUE THREAD

**Issue by BenjaminNavarro** [biojppm/rapidyaml#266]
While looking quickly at the code I often see things like:

```cpp
NodeRef operator[] (csubstr k)
{
    // [...]
    NodeRef r = ...;
    return r;
}

NodeRef const operator[] (csubstr k) const
{
    // [...]
    NodeRef const r = ...;
    return r;
}
```
I might be missing something but I see two problems with this pattern:
 1. having a const value as the return type makes no sense since the returned value can be assigned to a non-const one by making a copy
 2. returning a const value prevents moves which in turn prevents NRVO

See the [relevant clang-tidy check](https://releases.llvm.org/11.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/readability-const-return-type.html)

If you want constness propagated to returned values it must be encoded in the type. For instance you could have a `NodeConstRef` with only the const-qualified member functions of `NodeRef` and use that as a return type for such const-qualified functions.

**Comment by biojppm** [comment]
Thanks for the note. That is correct, and something that I've been meaning to address.
