### ISSUE TITLE
anchor in sequence dereferenced in a map fail, replaced by a scalar.

### ISSUE THREAD

**Issue by Schwartzp** [biojppm/rapidyaml#268]
I was using the library in order to parse a yaml to json.
I had this yaml as input : 

```
Constants:
  - &bar bar
Thisis: 
  ATree: *bar
```

Strangely instead of "{"ATree" : "bar"}  in the last map i had  "bar" in the json emitted document.

my code: 
```
std::string strIn; // input yaml string 
auto tree = ryml::parse_in_place(ryml::to_substr(strIn));
tree.resolve(); 
std::string out = ryml::emitrs_json<std::string>(tree);
```
Putting  " - bar: &bar bar"  in the first line of the yaml did the trick. But i believe this may be a bug.
Thanks for the library by the way !

**Comment by biojppm** [comment]
Thanks for reporting, and sorry for the late reply. Can you clarify exactly what you had as the result in `out`?

**Comment by Schwartzp** [comment]
From this code : 
```
#include <ryml_std.hpp>
#include <ryml.hpp>
#include <iostream>
int main(int argc,char*argv[]){
 std::string strIn ="\
Constants:\n\
  - &bar bar\n\
Thisis:\n\
  ATree: *bar";
 auto tree = ryml::parse_in_place(ryml::to_substr(strIn));
 tree.resolve();
 std::string out = ryml::emitrs_json<std::string>(tree);
 std::cout << out;
}
```
output is : 
{"Constants": ["bar"],"Thisis": {"bar"}}

I was expecting  {"Constants": ["bar"],"Thisis": {"Atree":"bar"}}

**Comment by Schwartzp** [comment]
No problem for me. 
Like i said putting the anchor in a map instead of a sequence work and is fine with my use.
I just reported to help the project. Thanks again.
