### ISSUE TITLE
No build shared library option in main cmake file

### ISSUE THREAD

**Issue by frankbenderumn** [biojppm/rapidyaml#270]
it would be nice if there was a shared library option available through the main cmake cli with a -DENABLE_SHARED or something similar

**Comment by frankbenderumn** [comment]
It also appears that you can't just return a simple string or char array. yaml-cpp doesn't have the tree structure so I switched here but you cant assign strings or use a shared lib. You should add these in the future. I will have to switch back to yaml-cpp

**Comment by biojppm** [comment]
Cmake has a standard variable for that: [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html)

**Comment by biojppm** [comment]
> It also appears that you can't just return a simple string or char array.
> 
> 
> 
> impressive library otherwise

Thanks for the compliment.

Regarding the issue, can you be more specific? I don't understand.
