### ISSUE TITLE
Should I keep string variable available after call parse_in_place ?

### ISSUE THREAD

**Issue by bigcat26** [biojppm/rapidyaml#276]
Is this safe: 

```c++
ryml::Tree my_parse(file) {
  char text[] = read(file);
  return ryml::parse_in_place(text);
}

void main() {
  auto tree = std::move(my_parse("somefile"));
  // manipulate tree instance here...
}
```

**Comment by biojppm** [comment]
No. When you parse in place, the tree will be pointing at the text buffer given to `parse_in_place()`, and when you return from your function the buffer is freed, so on main the tree will be pointing at dangling memory.

For this case you want `parse_in_arena()` which will copy the buffer to the tree's arena.
