### ISSUE TITLE
Merge fails with duplicate keys

### ISSUE THREAD

**Issue by stevebleazard** [biojppm/rapidyaml#277]
The following code using merge fails with error
  /tmp/pip-req-build-_e_q4qdk/src/c4/yml/tree.cpp:969:check_failed: (has_sibling(node, after) && has_sibling(after, node))
```
import ryml

src = """
A: &A
    V: 3
B:
    <<: *A
    V: 4
    W: 5
"""
tree = ryml.parse_in_arena(src)
tree.resolve()
```
Removing the V in B resolves the issue

**Comment by biojppm** [comment]
Thanks for reporting. Expect some time before this is looked at.
