### ISSUE TITLE
c4core subdirectory issing in ./ext

### ISSUE THREAD

**Issue by makingglitches** [biojppm/rapidyaml#278]
$ cmake ..
CMake Error at CMakeLists.txt:2 (include):
  include could not find requested file:

    ./ext/c4core/cmake/c4Project.cmake

CMake Error at CMakeLists.txt:9 (c4_project):
  Unknown CMake command "c4_project".

**Comment by biojppm** [comment]
The submodules were not checked out. Use git clone --recursive
