### ISSUE TITLE
Syntax error when emitting to JSON from a YAML versioning scheme value

### ISSUE THREAD

**Issue by captain-yoshi** [biojppm/rapidyaml#292]
Emitting a JSON file from a YAML with versioning value will give a SyntaxError when parsed in JSON.

YAML
``` yaml
james: 0.0.7
```
JSON
``` json
{"james": 0.0.7}
```
The versioning conversion to a double should not have passed (just a hypothesis).

**Comment by captain-yoshi** [comment]
@jppm I'm getting an unquoted versioning for `1.1.9` when converted to json.

Working versioning:
- `0.6.1`
- `0.0.0`

**Comment by biojppm** [comment]
That's odd. It succeeds with this:
```c++

TEST(emit_json, issue292)
{
    EXPECT_FALSE(csubstr("0.1.0").is_number());
    Tree t = parse_in_arena("{}");
    t["james"] = "1.2.3";
    EXPECT_EQ(emitrs_json<std::string>(t), "{\"james\": \"1.2.3\"}");
    t["james"] = "1.1.9";
    EXPECT_EQ(emitrs_json<std::string>(t), "{\"james\": \"1.1.9\"}");
    t["james"] = "0.6.1";
    EXPECT_EQ(emitrs_json<std::string>(t), "{\"james\": \"0.6.1\"}");
    t["james"] = "0.0.0";
    EXPECT_EQ(emitrs_json<std::string>(t), "{\"james\": \"0.0.0\"}");
}
```
Are you sure you have the latest version?

**Comment by captain-yoshi** [comment]
Latest version with rapidyaml. Does fetching rapidyaml through git also fetches the submodules ?

**Comment by captain-yoshi** [comment]
Forgot to update with `git submodule update --init --recursive` ... and made a PR to update this command in the docs... Oh well !
