### ISSUE TITLE
Extremely low performance on reading json files generated with ryml::emit_json

### ISSUE THREAD

**Issue by D-Alex** [biojppm/rapidyaml#301]
Thank you for the great library. We noticed a performance drop of several magnitudes if a bigger file is read, which was generated with ryml::emit_json. The reason is that no line breaks are added, making the parsing painfully slow. 

 A simple fix could be to change line https://github.com/biojppm/rapidyaml/blob/e1b57686eedd8fb8a5f6d2adc1043a98b8783732/src/c4/yml/emit.def.hpp#L492

to

    this->Writer::_do_write("}\n");

Performance measurements for parsing a 400KB json file:
* current implementation: 11014ms
* after the fix is applied: 22ms --> 500 times speedup

**Comment by biojppm** [comment]
Thanks! this was an egregious problem that was recently fixed. Which version or commit are you using?

**Comment by biojppm** [comment]
See #289 and #293

**Comment by D-Alex** [comment]
Thx for the quick response - We are currently using the header only release [rapidyaml-0.4.1.hpp](https://github.com/biojppm/rapidyaml/releases/download/v0.4.1/rapidyaml-0.4.1.hpp)

It seems the already merged fix is a proper fix for this issue as well 👍

**Comment by biojppm** [comment]
Got it, thanks. Closing this now; feel free to reopen #289 if it .
