### ISSUE TITLE
Is there a way of avoiding quotes when converting to JSON and back to YAML?

### ISSUE THREAD

**Issue by kdidkovsky** [biojppm/rapidyaml#316]
When an YAML is converted to JSON and back to YAML, single quotes are being added to most strings. Here's a small example:

```ryml::Tree tree;
  auto ref = tree.rootref();
  ref |= ryml::MAP;
  ref.append_child() << ryml::key("network") |= ryml::KEYMAP;
  auto network = ref["network"];
  network.append_child() << ryml::key("version") << "2";
  network.append_child() << ryml::key("renderer") << "NetworkManager";

  std::cout << "Source tree:" << std::endl << tree;
  auto json = ryml::emitrs_json<std::string>(tree);
  std::cout << std::endl << "->JSON:" << std::endl << json << std::endl;
  auto newTree = ryml::parse_in_arena(ryml::to_csubstr(json));
  std::cout << std::endl << "Converted back from JSON:" << std::endl << newTree;
  ```
  
  And the output produced looks like:
  
  ```
Source tree:
network:
  version: 2
  renderer: NetworkManager

->JSON:
{"network": {"version": 2,"renderer": "NetworkManager"}}

Converted back from JSON:
'network':
  'version': 2
  'renderer': 'NetworkManager'
```

Is there a way of telling the parser not to quote strings?

**Comment by biojppm** [comment]
When ryml is parsing, it marks nodes which were quoted in the source. That's done through the use of `NodeType_e` flags, specifically `KEYQUO` and/or `VALQUO`. 

At the same time, JSON is rather strict with the use of quotes, meaning most scalars will be quoted. As a consequence, a ryml-parsed JSON tree will have most nodes with the quote flags set. 

To prevent the quotes from being there when emitting YAML, after parsing you can simply clear the quote flags from each node. The style API is how that will/should be done in the future, but right now it is immature and under work. So for now you can do this:
```c++
Tree t = ...;
NodeRef node = tree....;
tree._rem_flags(node.id(), KEYQUO|VALQUO);
node.
```
If you want to do it on every node, just recurse through the tree to do it.

**Comment by biojppm** [comment]
@kdidkovsky did this help, or are you looking for something else?

**Comment by kdidkovsky** [comment]
> @kdidkovsky did this help, or are you looking for something else?

Yep, thanks a lot! I was manually removing extra quotes from the string generated, but I like your solution more, as it allows to clean up structured data instead of (probably error-prone) modifying raw buffer. I think that the issue may be closed now.
