### ISSUE TITLE
Begginers issue

### ISSUE THREAD

**Issue by LucasDamo22** [biojppm/rapidyaml#319]
Hi!
I've been working on a project where i need to work with yaml files, however, i've been having problems trying to read things using this library. I didn't find any video tutorials, and the quickstart samples aren't very friendly to dummies like me. Wondering if i can get some help? 
The task:
I have a Yaml file that has this structure:
Processes: 
  process1: [17, 500]
  process2: [ 4, 25]
  process3: [1, 75]
  process4: [20, 200]

then i need to read this integers, work with them, as variables, and then emit another Yaml file witih this structure:
Processes:
  operation1:[xx, xx]
  operation2:[xx, xx]
  operation3:[xx, xx]
  operation4:[xx, xx]

Can i have some guidance?

**Comment by biojppm** [comment]
Sorry, your question is too vague. There are too many points that you may be addressing on your question, and it is not possible to understand what they might be.

If you want concrete help, show me code of what you're trying to achieve and we can go from there.
