### ISSUE TITLE
Weird segfault when parsing a map in a sequence in some cases

### ISSUE THREAD

**Issue by leoetlino** [biojppm/rapidyaml#32]
The following document causes ryml to simply crash when parsing:

```yaml
- 'a': 1
  b: 2
```

These ones work, though:

```yaml
- a: 1
  b: 2
```

```yaml
- b: 2
  'a': 1
```

```yaml
- b: 2
  'a': 1
  c: 3
```

```yaml
'a': 1
b: 2
```

```yaml
b: 2
'a': 1
```

Using the inline flow style for the map in the problematic document also works:

```yaml
- {'a': 1, b: 2}
```

It looks like something goes wrong when parsing a map in a sequence, but only if the first key-value pair has a quoted key, and only if the map uses the block style.

**Comment by leoetlino** [comment]
Looks like the problem is that the indentation is mistakenly set to 4 rather than 2 from _handle_map_impl:

https://github.com/biojppm/rapidyaml/blob/e1216d4aabb53fa57795400ea110ddac7c57c1ea/src/c4/yml/parse.cpp#L1052-L1079

It appears that _save_indentation is being called with the length of the unquoted scalar.

**Comment by biojppm** [comment]
That's it, you nailed it.
