### ISSUE TITLE
Scalars should only be quoted if the string starts with @ or `

### ISSUE THREAD

**Issue by Gei0r** [biojppm/rapidyaml#320]
You recently merged #310, but I think it should only be checked if the emitted string *starts* with @ or backtick.

Although it's hard to tell from the spec.

Other yaml parsers seem to accept internal @ and backticks (while rejecting scalars starting with these chars).

**Comment by perlpunk** [comment]
Yes, correct, it's only a problem at the beginning.
https://www.yaml.info/learn/quote.html#noplain
