### ISSUE TITLE
Tab is not recognized as separator

### ISSUE THREAD

**Issue by NaN-git** [biojppm/rapidyaml#323]
When parsing sequences the tab character is not recognized as separator after the `-` token.

This seems to cause the failure of the parser e.g. when parsing this [YAML testcase](https://yaml.org/spec/1.2-old/spec.html#id2778101).
Also it prevents the recognition of sequences, e.g. when parsing the string `"-\tfoo"`.

**Comment by captain-yoshi** [comment]
Per the `known limitations` in the Readme:

> Tab characters after : and - are not accepted tokens, unless ryml is compiled with the macro RYML_WITH_TAB_TOKENS. This requirement exists because checking for tabs introduces branching into the parser's hot code and in some cases costs as much as 10% in parsing time.

Did you compiled with the necessary macro ?

**Comment by NaN-git** [comment]
Thank you. I already forgot this limitation. After enabling the macro it works as expected.
