### ISSUE TITLE
Move node to first position

### ISSUE THREAD

**Issue by a-w50** [biojppm/rapidyaml#324]
Hi,

is it possible to use the node ``move`` operation in order to move a node along it's siblings to the first place? Right now, there is only an ``after`` option. Using a NodeRef {tree, c4::yml::NONE } as after, doesn't seem to work, as it is not a sibling.

Thanks for this library!

**Comment by biojppm** [comment]
Did you [try this method](https://github.com/biojppm/rapidyaml/blob/74c80318daf52e2d6f1d314ed99d55c1bd69d0cf/src/c4/yml/node.hpp#L1116)? It should accept the empty `ConstNodeRef{tree, NONE}`.

 On the other hand, the [method that is given a parent](https://github.com/biojppm/rapidyaml/blob/74c80318daf52e2d6f1d314ed99d55c1bd69d0cf/src/c4/yml/node.hpp#L1125) will do consistency checks.

Maybe you're using this second method where you actually wanted the first?

**Comment by a-w50** [comment]
Thank you for your quick reply,

if I use this method, it will call https://github.com/biojppm/rapidyaml/blob/74c80318daf52e2d6f1d314ed99d55c1bd69d0cf/src/c4/yml/tree.cpp#L985 and there are the ``has_sibling`` checks, which fail for the ``NodeRef{tree, NONE}`` node, because it isn't part of the tree.  Or are there other ways to create/get this pseudo NodeRef?

**Comment by biojppm** [comment]
Ah, got it. This is a bug indeed.

But maybe you can work around it for now. Looking at this line:

https://github.com/biojppm/rapidyaml/blob/74c80318daf52e2d6f1d314ed99d55c1bd69d0cf/src/c4/yml/tree.cpp#L989

It seems that the assert there is not exactly right, and should accomodate `NONE`. It you change it to
```c++
_RYML_CB_ASSERT(m_callbacks, (after == NONE) || (has_sibling(node, after) && has_sibling(after, node)));
```
what happens? Let me know if it works. Or worst case, you can just call those functions on your own:
```c++
void mymove(Tree &tree, size_t node, size_t after)
{
    tree._rem_hierarchy(node);
    tree._set_hierarchy(node, parent(node), after);
}

(I will fix it on my own anyway and add proper unit tests, but for now it's just hard to get the time to look at it; the suggestions above are just to get you going quicker.)

**Comment by biojppm** [comment]
By the way, `_set_hierarchy()` accomodates it:

https://github.com/biojppm/rapidyaml/blob/74c80318daf52e2d6f1d314ed99d55c1bd69d0cf/src/c4/yml/tree.cpp#L631

**Comment by a-w50** [comment]
Right, I think there needs to be a check if it is NONE or not. I can't call ``_xxx_hierarchy`` because they are private.  Btw, I think the has_sibling routine is implemented quite expensive (`full` linear search), wouldn't it be enough to check if both have the same parent (with special treatment of the NONE of course).

**Comment by biojppm** [comment]
@a-w50 I prepared a PR, and improved the tests to address this scenario as well. The tests pass on my PC, but let's wait for the whole suite to finish in the CI. 

FWIW, you can move the subject node to the first position by simply doing
```c++
subject.move({});
```

**Comment by a-w50** [comment]
:+1: 
Concerning the `has_sibling` function, wouldn't it be easier to check if both have the same parent, instead of searching each other?
