### ISSUE TITLE
Formatting possibilies

### ISSUE THREAD

**Issue by a-w50** [biojppm/rapidyaml#325]
Hi,

I have seen that there have been already some issues addressing formatting possibilities.  What is the current status?
The problem I'm currently facing is when loading JSON files and emitting them as YAML, everything is enclosed by single quotes - but I would like to let the emitted YAML look more like plain YAML (of course, in some cases, keys and values need to be quoted).
Where would be a starting point in the code to "enhance" formatting like this?

Thanks!

**Comment by biojppm** [comment]
See #316

**Comment by a-w50** [comment]
Thank you so much. I wasn't aware of this issue - exactly what I was looking for!
