### ISSUE TITLE
Question: Importing Library giving errors

### ISSUE THREAD

**Issue by KaylaBCronk** [biojppm/rapidyaml#327]
Forgive me once again for asking a silly question, but I have a feeling I'm doing something (that could be simplified) wrong. 

My team has decided to move forward with Rapid Yaml (we're impressed!) We are currently using the it as a library (.lib, .dll, and includes hpp files) I currently have the latest I grabbed from your ci run. (So I know the source code is up to date.)  Our current code is: 

```
#include <ryml/ryml.hpp>
#include <c4/format.hpp>

int TransformYaml(CStdString& str)
{
	std::string json = (char*)(LPCTSTR)str;
	ryml::Tree tree = ryml::parse_in_place(c4::to_substr(json));
	json = ryml::emitrs_json<std::string>(tree);
	int jsonLength = json.length();
	strncpy((char*)str.GetBuffer(jsonLength), json.c_str(), jsonLength);
	str.ReleaseBuffer(jsonLength);
	return jsonLength;
}
```
Previously we were using the single header file (so we know this code works well), but after consideration we have decided to move to the library route. 

Ever since importing it into our VS2019 project, I've been getting errors from the substr.hpp class as well as the charcov.hpp class. (158 to be exact). Within the substr class a lot of the errors appear to be coming from the C4_PURE variable. 
![image](https://user-images.githubusercontent.com/115042152/202579846-96625158-a7b3-4ce5-90b8-c9a9433b124c.png)

That all being said - maybe I'm including the wrong files? Maybe my properties within our VS project are wrong for building? Any insight is much appreciated!

**Comment by biojppm** [comment]
How are you "importing" into the VS project? How are you building ryml itself before importing?

**Comment by KaylaBCronk** [comment]
For importing: We're taking the necessary files, placing them were our project can grab them. Then importing them into the project we need by using the properties tab. Importing the .lib files in Linker>Input>Additional Dependencies and the includes directories in C/C++>General> Additional Include Directories. 

As for building ryml itself, we're not (and maybe that's where we're going wrong.) We're simply grabbing the necessary files from a package manager (.lib,.dll, and .hpp) and throwing them where we need.

**Comment by biojppm** [comment]
From the description it is hard to tell what may be going on. I will need the text output of the compiler to  to get a better idea. Compile your file in VS (eg Ctrl-F7), and copy-paste it here.

**Comment by KaylaBCronk** [comment]
```
1>C:\build\SDKDIR\include\c4\substr.hpp(193,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(2103): message : see reference to class template instantiation 'c4::basic_substring<C>' being compiled
1>C:\build\SDKDIR\include\c4\substr.hpp(193,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(193,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(194,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(194,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(194,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(195,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(195,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(195,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(196,30): error C3646: 'size_t': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(196,37): error C3646: 'size': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(196,42): error C2059: syntax error: ')'
1>C:\build\SDKDIR\include\c4\substr.hpp(196,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(198,30): error C3646: 'iterator': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(198,39): error C3646: 'begin': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(198,45): error C2059: syntax error: ')'
1>C:\build\SDKDIR\include\c4\substr.hpp(198,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(199,30): error C3646: 'iterator': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(199,39): error C3646: 'end': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(199,45): error C2059: syntax error: ')'
1>C:\build\SDKDIR\include\c4\substr.hpp(199,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(201,30): error C3646: 'const_iterator': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(201,45): error C3646: 'begin': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(201,51): error C2059: syntax error: ')'
1>C:\build\SDKDIR\include\c4\substr.hpp(201,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(202,30): error C3646: 'const_iterator': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(202,45): error C3646: 'end': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(202,51): error C2059: syntax error: ')'
1>C:\build\SDKDIR\include\c4\substr.hpp(202,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(204,30): error C3646: 'C': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(204,37): error C2143: syntax error: missing ';' before '*'
1>C:\build\SDKDIR\include\c4\substr.hpp(204,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(204,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(204,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(205,30): error C3646: 'C': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(205,32): error C2143: syntax error: missing ';' before 'const'
1>C:\build\SDKDIR\include\c4\substr.hpp(205,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(205,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(207,30): error C3646: 'C': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(207,37): error C2143: syntax error: missing ';' before '&'
1>C:\build\SDKDIR\include\c4\substr.hpp(207,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(207,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(207,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(208,30): error C3646: 'C': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(208,32): error C2143: syntax error: missing ';' before 'const'
1>C:\build\SDKDIR\include\c4\substr.hpp(208,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(208,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(210,30): error C3646: 'C': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(210,37): error C2143: syntax error: missing ';' before '&'
1>C:\build\SDKDIR\include\c4\substr.hpp(210,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(210,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(210,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(211,30): error C3646: 'C': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(211,32): error C2143: syntax error: missing ';' before 'const'
1>C:\build\SDKDIR\include\c4\substr.hpp(211,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(211,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(213,30): error C3646: 'C': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(213,37): error C2143: syntax error: missing ';' before '&'
1>C:\build\SDKDIR\include\c4\substr.hpp(213,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(213,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(213,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(214,30): error C3646: 'C': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(214,32): error C2143: syntax error: missing ';' before 'const'
1>C:\build\SDKDIR\include\c4\substr.hpp(214,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(214,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(223,13): error C2144: syntax error: 'int' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(223,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(232,13): error C2144: syntax error: 'int' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(232,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(259,30): error C2144: syntax error: 'int' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(259,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(259,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(261,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(261,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(261,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(262,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(262,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(262,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(264,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(264,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(264,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(265,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(265,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(265,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(266,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(266,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(266,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(267,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(267,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(267,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(268,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(268,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(268,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(269,30): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(269,1): error C2433: 'c4::basic_substring<C>::C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(269,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(271,48): error C2144: syntax error: 'bool' should be preceded by ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(271,1): error C2433: 'C4_PURE': '__forceinline' not permitted on data declarations
1>C:\build\SDKDIR\include\c4\substr.hpp(271,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\build\SDKDIR\include\c4\substr.hpp(271,1): error C2238: unexpected token(s) preceding ';'
1>C:\build\SDKDIR\include\c4\substr.hpp(271,1): error C2988: unrecognizable template declaration/definition
1>C:\build\SDKDIR\include\c4\substr.hpp(271,1): error C2059: syntax error: '<end Parse>'
1>C:\build\SDKDIR\include\c4\substr.hpp(609,25): error C3646: 'first_of_any': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(609,37): error C2988: unrecognizable template declaration/definition
1>C:\build\SDKDIR\include\c4\substr.hpp(609,37): error C2059: syntax error: '('
1>C:\build\SDKDIR\include\c4\substr.hpp(610,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(615,25): error C3646: 'first_of_any': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(615,37): error C2988: unrecognizable template declaration/definition
1>C:\build\SDKDIR\include\c4\substr.hpp(615,37): error C2059: syntax error: '('
1>C:\build\SDKDIR\include\c4\substr.hpp(616,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(621,25): error C3646: 'first_of_any': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(621,37): error C2988: unrecognizable template declaration/definition
1>C:\build\SDKDIR\include\c4\substr.hpp(621,37): error C2059: syntax error: '('
1>C:\build\SDKDIR\include\c4\substr.hpp(622,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(627,25): error C3646: 'first_of_any': unknown override specifier
1>C:\build\SDKDIR\include\c4\substr.hpp(627,37): error C2988: unrecognizable template declaration/definition
1>C:\build\SDKDIR\include\c4\substr.hpp(627,37): error C2059: syntax error: '('
1>C:\build\SDKDIR\include\c4\substr.hpp(628,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(634,25): error C2061: syntax error: identifier 'first_of_any_iter'
1>C:\build\SDKDIR\include\c4\substr.hpp(635,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(667,9): error C2988: unrecognizable template declaration/definition
1>C:\build\SDKDIR\include\c4\substr.hpp(667,9): error C2059: syntax error: 'return'
1>C:\build\SDKDIR\include\c4\substr.hpp(667,1): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
1>C:\build\SDKDIR\include\c4\substr.hpp(673,9): error C2988: unrecognizable template declaration/definition
1>C:\build\SDKDIR\include\c4\substr.hpp(673,1): fatal error C1003: error count exceeds 100; stopping compilation
```

**Comment by biojppm** [comment]
Is this the full log?

the first reported error [points at this](https://github.com/biojppm/c4core/blob/24d06bbaf5f3509f05879c0cfcfc1462f8911efc/src/c4/substr.hpp#L193), around C4_PURE:
```c++
    C4_ALWAYS_INLINE C4_PURE bool   has_str()   const noexcept { return ! empty() && str[0] != C(0); }
```
... and `C4_PURE` is [defined in this line](https://github.com/biojppm/c4core/blob/24d06bbaf5f3509f05879c0cfcfc1462f8911efc/src/c4/language.hpp#L216), somehow like sketched below:
```c++
#ifndef _MSC_VER
// ... attributes for gcc-like compilers
#else
// ... attributes for Visual Studio, among which:
#define C4_PURE     /* nothing */
#endif
```
Could it be that `_MSC_VER` is not defined in your project? Generally, this macro is defined by Visual Studio, and rapidyaml/c4core relies on it heavily to define the macros appropriately for VisualStudio.

What happens if you add this on your file?
```c++
#ifndef _MSC_VER
#error "uh-oh"
#endif
```

**Comment by KaylaBCronk** [comment]
It's not the full log as once the error count gets to 100 it stops the compilation. (In total there's around 148 errors.) 

That's why I've been having such a hard time battling this as everything substr.hpp needs is defined in language.hpp. _MSC_VER is unfortunately defined in our project, so adding in those 3 lines doesn't change anything. 

One thing to mention is I have ryml 0.4.1 from vcpckg on my machine, and if I replace the current substr.hpp file with the 0.4.1 substr.hpp I don't have any errors. 

If I define the needed variables in substr.hpp it's not picking up from language.hpp:
```
#define C4_ALWAYS_INLINE inline __forceinline
#define C4_PURE
#define C4_CONST
```
Then the errors move off of substr.hpp into charcov.hpp 

`>C:\build\SDKDIR\include\c4\charconv.hpp(1895,25): error C2065: 'ipow': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1971): message : see reference to function template instantiation 'bool c4::detail::scan_rhex<float>(c4::csubstr,T *__restrict ) noexcept' being compiled
1>        with
1>        [
1>            T=float
1>        ]
1>C:\build\SDKDIR\include\c4\charconv.hpp(1895,30): error C2275: 'T': illegal use of this type as an expression
1>C:\build\SDKDIR\include\c4\charconv.hpp(1024,13): error C2589: '(': illegal token on right side of '::'
1>C:\build\SDKDIR\include\c4\charconv.hpp(2069): message : see reference to function template instantiation 'size_t c4::itoa<int8_t>(c4::substr,T) noexcept' being compiled
1>        with
1>        [
1>            T=int8_t
1>        ]
1>C:\build\SDKDIR\include\c4\charconv.hpp(1024): error C2062: type 'unknown-type' unexpected
1>C:\build\SDKDIR\include\c4\charconv.hpp(1024,1): error C2059: syntax error: ')'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1025,1): error C2143: syntax error: missing ';' before '{'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1035,5): error C2059: syntax error: 'return'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1035,33): error C2065: 'T': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1036,1): error C2059: syntax error: '}'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1036,1): error C2143: syntax error: missing ';' before '}'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1015,1): error C2143: syntax error: missing ';' before '{'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1015,1): error C2447: '{': missing function header (old-style formal list?)
1>C:\build\SDKDIR\include\c4\charconv.hpp(1056,8): error C2589: '(': illegal token on right side of '::'
1>C:\build\SDKDIR\include\c4\charconv.hpp(2080): message : see reference to function template instantiation 'size_t c4::itoa<int8_t>(c4::substr,T,T) noexcept' being compiled
1>        with
1>        [
1>            T=int8_t
1>        ]
1>C:\build\SDKDIR\include\c4\charconv.hpp(1056): error C2062: type 'unknown-type' unexpected
1>C:\build\SDKDIR\include\c4\charconv.hpp(1056,1): error C2059: syntax error: ')'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1057,1): error C2143: syntax error: missing ';' before '{'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1063,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1064,15): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1071,16): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1072,45): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1072,17): error C2672: 'c4::write_dec_unchecked': no matching overloaded function found
1>C:\build\SDKDIR\include\c4\charconv.hpp(1076,16): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1078,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1079,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1080,45): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1080,17): error C2672: 'c4::write_hex_unchecked': no matching overloaded function found
1>C:\build\SDKDIR\include\c4\charconv.hpp(1086,16): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1088,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1089,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1090,45): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1090,17): error C2672: 'c4::write_bin_unchecked': no matching overloaded function found
1>C:\build\SDKDIR\include\c4\charconv.hpp(1096,16): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1098,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1099,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1100,45): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1100,17): error C2672: 'c4::write_oct_unchecked': no matching overloaded function found
1>C:\build\SDKDIR\include\c4\charconv.hpp(1105,16): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1110,5): error C2059: syntax error: 'return'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1110,30): error C2065: 'T': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1111,1): error C2059: syntax error: '}'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1111,1): error C2143: syntax error: missing ';' before '}'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1047,1): error C2143: syntax error: missing ';' before '{'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1047,1): error C2447: '{': missing function header (old-style formal list?)
1>C:\build\SDKDIR\include\c4\charconv.hpp(1133,8): error C2589: '(': illegal token on right side of '::'
1>C:\build\SDKDIR\include\c4\charconv.hpp(2089): message : see reference to function template instantiation 'size_t c4::itoa<int8_t>(c4::substr,T,T,size_t) noexcept' being compiled
1>        with
1>        [
1>            T=int8_t
1>        ]
1>C:\build\SDKDIR\include\c4\charconv.hpp(1133): error C2062: type 'unknown-type' unexpected
1>C:\build\SDKDIR\include\c4\charconv.hpp(1133,1): error C2059: syntax error: ')'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1134,1): error C2143: syntax error: missing ';' before '{'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1140,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1141,15): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1148,28): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1150,35): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1150,17): error C2672: 'c4::write_dec': no matching overloaded function found
1>C:\build\SDKDIR\include\c4\charconv.hpp(1150,1): error C2780: 'size_t c4::write_dec(c4::substr,T) noexcept': expects 2 arguments - 3 provided
1>C:\build\SDKDIR\include\c4\charconv.hpp(641): message : see declaration of 'c4::write_dec'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1154,28): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1157,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1158,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1159,35): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1159,17): error C2672: 'c4::write_hex': no matching overloaded function found
1>C:\build\SDKDIR\include\c4\charconv.hpp(1159,1): error C2780: 'size_t c4::write_hex(c4::substr,T) noexcept': expects 2 arguments - 3 provided
1>C:\build\SDKDIR\include\c4\charconv.hpp(660): message : see declaration of 'c4::write_hex'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1164,28): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1167,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1168,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1169,35): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1169,17): error C2672: 'c4::write_bin': no matching overloaded function found
1>C:\build\SDKDIR\include\c4\charconv.hpp(1169,1): error C2780: 'size_t c4::write_bin(c4::substr,T) noexcept': expects 2 arguments - 3 provided
1>C:\build\SDKDIR\include\c4\charconv.hpp(698): message : see declaration of 'c4::write_bin'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1174,28): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1177,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1178,25): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1179,35): error C2065: 'pos': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1179,17): error C2672: 'c4::write_oct': no matching overloaded function found
1>C:\build\SDKDIR\include\c4\charconv.hpp(1179,1): error C2780: 'size_t c4::write_oct(c4::substr,T) noexcept': expects 2 arguments - 3 provided
1>C:\build\SDKDIR\include\c4\charconv.hpp(679): message : see declaration of 'c4::write_oct'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1188,5): error C2059: syntax error: 'return'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1188,30): error C2065: 'T': undeclared identifier
1>C:\build\SDKDIR\include\c4\charconv.hpp(1189,1): error C2059: syntax error: '}'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1189,1): error C2143: syntax error: missing ';' before '}'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1124,1): error C2143: syntax error: missing ';' before '{'
1>C:\build\SDKDIR\include\c4\charconv.hpp(1124,1): error C2447: '{': missing function header (old-style formal list?)`

**Comment by biojppm** [comment]
Then this smells like you have a tainted include path, and it's including the wrong c4core. You can check this by placing something like
```c++
#ifndef C4_PURE
#error "uh-oh, old c4core being included"
#endif
```
in your source file, after the includes.

This should trigger a compile error with the message above. If it is confirmed, all you have to do is ensuring that the old version is nowhere in your include path.

**Comment by KaylaBCronk** [comment]
Ugh, you were right - I've been trying to get this to work so persistently I lost a c4 directory in my source code that never got deleted. Thank you! 

One last error that I can't seem to resolve that you might have some insight into - 
`1>wsclntprocs.obj : error LNK2019: unresolved external symbol "struct c4::basic_substring<char> __cdecl c4::to_substr(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?to_substr@c4@@YA?AU?$basic_substring@D@1@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "struct c4::basic_substring<char> __cdecl c4::yml::emitrs_json<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class c4::yml::Tree const &,unsigned __int64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??$emitrs_json@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@yml@c4@@YA?AU?$basic_substring@D@1@AEBVTree@01@_KPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
`

This appears to be coming from the .lib c4core.lib file, is the to_substr no longer in use?

**Comment by biojppm** [comment]
Looks like it is missing include of `ryml_std.hpp` (if you're using `ryml.hpp`) or `c4/std/string.hpp`  (if you're using `c4/yml/parse.hpp` et al)

**Comment by biojppm** [comment]
I guess you are including `windows.h` or some other Windows header? They define a `min` macro. To avoid that macro you can define `NOMINMAX` **before** including `windows.h`
 * https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std
 * https://stackoverflow.com/questions/13416418/define-nominmax-using-stdmin-max
