### ISSUE TITLE
has_sibling() is inefficient

### ISSUE THREAD

**Issue by biojppm** [biojppm/rapidyaml#329]
> in the `has_sibling` function, wouldn't it be easier to check if both have the same parent, instead of searching each other?

_Originally posted by @a-w50 in https://github.com/biojppm/rapidyaml/issues/324#issuecomment-1320272566_

**Comment by biojppm** [comment]
@a-w50 thanks for reporting. indeed, that is a quicker way. IIRC, on the first iterations of the data-structure there was no parent info, and this implementation just lingered from that time.

**Comment by a-w50** [comment]
Thanks for taking care :)
