### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by NaN-git** [biojppm/rapidyaml#331]
# Description

When parsing YAML without line breaks and with many scalars, then the parser becomes arbitrary slow. Often JSON has such a format.

The cause of the issue seems to be [this line of code](https://github.com/biojppm/rapidyaml/blob/master/src/c4/yml/parse.cpp#L4247). I don't understand the purpose of the check, but it causes the scanning of the whole line, if the line contains no `\r`-character, i.e. the complexity to scan the line becomes `#scalars x #characters`. Removing the check (for testing) fixes the performance issue for my test case. The same check appears in other functions, too, i.e. those functions will be affected, too.

It seems to be a mistake that the scan starts outside of the scalar at the end of the line because the filtering is applied to the scalar only.

**Comment by biojppm** [comment]
Thanks for reporting, and allow some time for investigating the problem.

**Comment by biojppm** [comment]
@NaN-git First, are you using an older version? Since the last release there was a performance fix for a similar problem (#289, see PR #293). The current master branch has this fix.

If this is the master we are speaking of, then can you provide an example of YAML which triggers this behavior?

**Comment by NaN-git** [comment]
@biojppm Yes, I'm using master. I updated the link in the issue to link to master, too.

This ~300KB [test file](https://github.com/biojppm/rapidyaml/files/10098505/small-test-case.txt) takes nearly 1s for parsing and when the file is re-formatted with line breaks, then parsing is very quick. On another 54MB file parsing took more than 10 minutes.

**Comment by biojppm** [comment]
To be honest I don't recall exactly why I put that line there, so I tried removing it, and all the unit tests succeeded. 

> I'm using Linux, i.e. my line ending is `\n` and not `\r\n`. Probably this issue will not show up if the line ending is `\r\n`.

The unit tests explicitly add `\r` to every line and cover both cases (Unix and Windows line endings), so removing is definitely alright vis-a-vis correctness, since all the tests pass. But performance tests are harder to get right, so that's why you are seeing the problem.

But the good news is that by removing that line, parsing your file in Debug/Release went from 4162ms/1105ms to 10.9ms/5.6ms.

First with the offending line:

```console
# with the offending line, Debug
$ ./build/Debug/tools/ryml-parse-emit small-test-case.yml 1>/dev/null
0.431575ms: read_file
1.594471ms: count_lines
reserving #lines=1
1.621998ms: tree_reserve
4171.769160ms: parse_yml
6.086949ms: emit_to_buffer
0.009583ms: print_stdout
4180.102102ms: objects
4180.125516ms: TOTAL

# with the offending line, Release
$ ./build/Release/tools/ryml-parse-emit small-test-case.yml 1>/dev/null
0.264311ms: read_file
0.155279ms: count_lines
reserving #lines=1
0.165339ms: tree_reserve
1110.449055ms: parse_yml
1.508306ms: emit_to_buffer
0.007926ms: print_stdout
1112.508931ms: objects
1112.524354ms: TOTAL
```

and then removing that line results in the following:

```console
# without the offending line, Debug
$ ./build/Debug/tools/ryml-parse-emit small-test-case.yml 1>/dev/null
0.445101ms: read_file
1.609665ms: count_lines
reserving #lines=1
1.637494ms: tree_reserve
10.962819ms: parse_yml
6.482148ms: emit_to_buffer
0.015330ms: print_stdout
19.744460ms: objects
19.767127ms: TOTAL

# without the offending line, Release
$ ./build/Release/tools/ryml-parse-emit small-test-case.yml 1>/dev/null
0.433004ms: read_file
0.347704ms: count_lines
reserving #lines=1
0.363569ms: tree_reserve
5.571111ms: parse_yml
1.601619ms: emit_to_buffer
0.011489ms: print_stdout
8.160416ms: objects
8.184868ms: TOTAL
```

So I'm just going to commit this and your problem should be fixed.

**Comment by NaN-git** [comment]
@biojppm This fix isn't complete. The same line also appears in `Parser::_scan_squot_scalar`.

**Comment by biojppm** [comment]
Thanks for the attentive eye. Fix follows.
