### ISSUE TITLE
Incorrect handling of quoted scalars in some cases

### ISSUE THREAD

**Issue by leoetlino** [biojppm/rapidyaml#34]
Thanks for fixing #32. I ran some parsing tests and it looks like there are issues with the handling of quoted scalars:

The problematic document is as follows:

```yaml
-  MessageID: 'MapRegion_HyrulePrairie '
```

Note that the string contains a trailing whitespace, which is incidentally why it has to be quoted.

Now, rapidyaml appears to be having trouble with such scalars:

```python
>>> parse("-  MessageID:          'MapRegion_HyrulePrairie'").v[0]
Byml(Map({'MessageID': Byml("MapRegion_HyrulePrairie'o\x00\x00\x00r\x00\x00\x00y")}))
# incorrect: uninitialised memory?

>>> parse("-  MessageID:          'MapRegion_HyrulePrairie '").v[0]
Byml(Map({'MessageID': Byml("MapRegion_HyrulePrairie 'FM\x02\x00\x00\x00\x00\x01\x00")}))
# incorrect: uninitialised memory?

>>> parse("-  MessageID: 'MapRegion_HyrulePrairie '").v[0]
Byml(Map({'MessageID': Byml("MapRegion_HyrulePrairie '")}))
# incorrect: for some reason the ' is included in the string

>>> parse("- MessageID: 'MapRegion_HyrulePrairie '").v[0]
Byml(Map({'MessageID': Byml("MapRegion_HyrulePrairie '")}))
# incorrect: same issue

>>> parse("- MessageID: 'MapRegion_HyrulePrairie'").v[0]
Byml(Map({'MessageID': Byml("MapRegion_HyrulePrairie'")}))
# incorrect: still has the trailing quote

>>> parse("- key: true\n MessageID:          'MapRegion_HyrulePrairie '").v[0]
# *segfault*

>>> parse("- key: true\n  MessageID:          'MapRegion_HyrulePrairie '").v[0]
Byml(Map({'MessageID': Byml('MapRegion_HyrulePrairie '), 'key': Byml(True)}))
# the string is parsed correctly in this case
```

https://github.com/leoetlino/rapidyaml/commit/00c665e9dfc684d8b7c0b6dcb543f8fce187082d prevents the issue from manifesting but obviously that is not the right fix since it probably breaks multi-line scalars.

**Comment by biojppm** [comment]
@leoetlino thanks for the writeup, I really appreciate.

quick note:
```python
>>> parse("- key: true\n MessageID:          'MapRegion_HyrulePrairie '").v[0]
# *segfault*
```
This is expected: the MessageID on the second line is wrongly indented. It requires the same indentation of the previous line to be valid YAML. It's easy to see if you write it explicitly:
```yaml
- key: true
 MessageID:          'MapRegion_HyrulePrairie ' # WRONG indentation different from previous line
```
The example you show next succeeds precisely because of this:
```yaml
- key: true
  MessageID:          'MapRegion_HyrulePrairie ' # OK, indentation same as previous line
```

Also, FWIW, are you actually seeing a segfault? Likely what you are seeing are legimitate errors flagged by ryml through calls to `c4::yml::error()`.

**Comment by leoetlino** [comment]
Yep, which is why I mentioned it. It's invalid YAML but for some reason rather than error() being called (and my custom error handler throwing an exception) the entire program crashes. It's odd because other parse errors do result in the error handler being called.

**Comment by biojppm** [comment]
Well - thanks for letting me know of this error. It really should trigger a call to c4::yml:: error().

I'm filing this as a separate bug, as it seems related to indentation.

**Comment by biojppm** [comment]
The bug was similar to #32 .

**Comment by biojppm** [comment]
Thanks!

**Comment by leoetlino** [comment]
Fantastic, thanks for the fix!

**Comment by biojppm** [comment]
Thanks for sticking. ryml is still very fresh, and still requires some improvements for less canonical YAML. Your bug reports are definitely helping.
