### ISSUE TITLE
Serialize boolean types as "true"/"false"

### ISSUE THREAD

**Issue by dbarkar** [biojppm/rapidyaml#355]
YAML 1.2 spec resolves this expression to boolean tag: `true | True | TRUE | false | False | FALSE`, while rapidyaml emitting booleans as ints:
```
inline size_t to_chars(substr buf, bool v)
{
    int val = v;
    return to_chars(buf, val);
}
```
I suggest emitting "true" and "false" values.

p.s> Currently, what is the best way to emit boolean as text?

**Comment by biojppm** [comment]
Bools are emitted as 0/1 just like if you print to `std::cout`. The behaviour is similar also in emitting as `true/false`.

There is an example of that in the quickstart. Search for `"true"`. 

Sorry for the brevity, but I'm away from the PC and limited internet access.

**Comment by dbarkar** [comment]
Thanks for the tip! 
Sorry for confusion, looks like I didn't get the idea - so the formatter must be used in this case. I guess we can close the issue :)
