### ISSUE TITLE
Linking Issues

### ISSUE THREAD

**Issue by Hatrickek** [biojppm/rapidyaml#360]
I build my lib project as static in runtime library /MT mode. I have added rapidyaml in cmake like this:
```
# RYML
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}\\vendor\\ryml)
target_link_libraries(${PROJECT_NAME} PUBLIC ryml::ryml)
set_target_properties(ryml PROPERTIES MSVC_RUNTIME_LIBRARY ${MSVC_RUNTIME_LIBRARY_STR})
target_link_libraries(${PROJECT_NAME} PUBLIC c4core)
set_target_properties(c4core PROPERTIES MSVC_RUNTIME_LIBRARY ${MSVC_RUNTIME_LIBRARY_STR})
```
I have set both c4core and ryml to /MT so there is no mismatch with my lib project. Then I link this static lib project with my exe project.
```
# Link with oxylus.
target_link_libraries(${PROJECT_NAME} PRIVATE
    Oxylus
)
```
When I build I the exe project I get bunch of c4core linking errors like this:
```
LNK2001: unresolved external symbol "struct c4::basic_substring<char const > __cdecl c4::to_csubstr(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?to_csubstr@c4@@YA?AU?$basic_substring@$$CBD@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
```
Is there a macro definition I'm missing for building static or is there something else I'm overlooking?

**Comment by biojppm** [comment]
Probably you are missing an `#include <c4/yml/std/string.hpp>`, or of the umbrella `#include <ryml_std.hpp>`.  This is [mentioned in the quickstart](https://github.com/biojppm/rapidyaml/blob/7c0036e7c41318ec75368f9a2b2148c31b3121db/samples/quickstart.cpp#L34).

**Comment by Hatrickek** [comment]
Adding `#include <c4/yml/std/string.hpp>` fixed my issue thanks 👍
