### ISSUE TITLE
Assert while parsing valid yaml with ':' in text

### ISSUE THREAD

**Issue by svart-riddare** [biojppm/rapidyaml#361]
While parsing:

```
value:
  description:
    Timecode in "HH:MM:SS:FF" format where the last ':' can be replaced by ',' or ';'.
```

rapidyam 0.5.0 asserts in `csubstr Parser::_consume_scalar()`, on `RYML_CHECK(m_state->flags & SSCL);`.

YAML contains tricky ":" in text string but is considered valid by online validators and is read correctly by libyaml.

**Comment by biojppm** [comment]
Thanks for reporting. Allow some time before this is fixed.

**Comment by svart-riddare** [comment]
Thank you for your quick reply. Take your time, I raised this issue mostly because I saw it; I can workaround it as follow:

```
value:
  description: >-
    Timecode in "HH:MM:SS:FF" format where the last ':' can be replaced by ',' or ';'.
```

**Comment by biojppm** [comment]
Finally looking at this.

FWIW, [this smaller example fails the same way](https://play.yaml.io/main/parser?input=dmFsdWU6CiAgZGVzY3JpcHRpb246IAogICAgZm9vOmJhcgo=):
```yaml
value:
  description: 
    foo:bar
```
while [this succeeds](https://play.yaml.io/main/parser?input=dmFsdWU6CiAgZGVzY3JpcHRpb246IGZvbzpiYXIK):
```yaml
value:
  description: foo:bar
```
and [this succeeds as well](https://play.yaml.io/main/parser?input=dmFsdWU6CiAgZGVzY3JpcHRpb246IFRpbWVjb2RlIGluICJISDpNTTpTUzpGRiIgZm9ybWF0IHdoZXJlIHRoZSBsYXN0ICc6JyBjYW4gYmUgcmVwbGFjZWQgYnkgJywnIG9yICc7Jy4K):
```yaml
value:
  description: Timecode in "HH:MM:SS:FF" format where the last ':' can be replaced by ',' or ';'.
```

**Comment by svart-riddare** [comment]
Thanks !
