### ISSUE TITLE
Error C2665 "c4::to_chars" : No overloaded function can convert all parameter types

### ISSUE THREAD

**Issue by TheSonder** [biojppm/rapidyaml#366]
Severity Code Description The project file line does not display the status
Error C2665 "c4::to_chars" : No overloaded function can convert all parameter types (compile the source file src\Halo\Serializer\Serializer.cpp)	Halo	E:\User\Code\MyCodeRepository\RT\Halo\Halo\vendor\rapidyaml\src\c4\yml\tree.hpp 	1029

I use this code:
```c_cpp
#include <Pangea/Pangea.h> // need for pgag::point<T, N>
#include <ryml.hpp>
#include <ryml_std.hpp>

#include <c4/format.hpp> 



template<class T> size_t to_chars(ryml::substr buf, pgag::vec<T, 3>& v) { return ryml::format(buf, "({},{},{})", v.x, v.y, v.z); }
template<class T> size_t to_chars(ryml::substr buf, pgag::point<T, 3>& v) { return ryml::format(buf, "({},{},{})", v.x, v.x, v.x); }

namespace Some{
  void Parse()
  {
     pgag::point<float, 3> point;
     ryml::NodeRef out;
     ryml::Tree tree;
     ryml::NodeRef root = tree.rootref();
     out = root["Point"];
     out << point;
  }
}

```

**Comment by biojppm** [comment]
There are three simultaneous problems with your `to_chars()` implementations:

   * they are not declared in the proper namespace, so argument-dependent lookup fails. To fix this, they should be declared in the `pgag` namespace. 
   * they take the value by non-const reference, so they will not participate in overload resolution, as the compiler will be looking for const reference overloads.
   * the version for `pgag::point<T,3>` is only converting `(v.x,v.x,v.x)`.

**Comment by TheSonder** [comment]
> There are three simultaneous problems with your `to_chars()` implementations:
> 
> * they are not declared in the proper namespace, so argument-dependent lookup fails. To fix this, they should be declared in the `pgag` namespace.
> * they take the value by non-const reference, so they will not participate in overload resolution, as the compiler will be looking for const reference overloads.
> * the version for `pgag::point<T,3>` is only converting `(v.x,v.x,v.x)`.

Thank you for your answer. And according to your tutorial I have solved the problem in declared in the proper namespace.And  the value already be taked by non-const reference.
Thank you very much.
