### ISSUE TITLE
Emitting in flow style

### ISSUE THREAD

**Issue by ZhouYe890** [biojppm/rapidyaml#370]
Can the following be done when creating nodes, which enhances the readability of the file.
explain: 
   - {key: a, desc: b}
   - {key: c, desc: d}
We look forward to your reply.
Kind regards,
zhou

**Comment by biojppm** [comment]
Sorry, I don't understand your question. Can you be more specific?

**Comment by ZhouYe890** [comment]
Firstly, I am glad to receive your reply. When I was adding data, I found that data can only be added in the form of one key value pair per row, as shown in the following situation:
NodeOne:
     - key: a
       desc: b
       class: c
       number: d
     - key: e
       desc: f
       class: g
       number: h
     - key: i
       desc: j
       class: k
       number: l
   If the data volume is large, it will inevitably increase the number of lines in the configuration file. If data can be added as follows, it will inevitably make the entire file structure clearer.
NodeOne:
     - {key: a, desc: b, class: c, number: d}
     - {key: e, desc: f, class: g, number: h}
     - {key: i, desc: j, class: k, number: l}

**Comment by biojppm** [comment]
There are some [experimental style flags which you can set on the nodes](https://github.com/biojppm/rapidyaml/blob/ff1a9858b1aa667dfef3267bc467596132f657be/src/c4/yml/tree.hpp#L174). 

For example, after parsing (or after creating the tree), and ***before*** emitting, set the flow style for the specific nodes you want:
```c++
for(NodeRef child : tree["NodeOne"].children())
    child |= _WIP_STYLE_FLOW_SL;

// now emit. the node will be emitted in single-line flow style
emit(tree);
```

**Comment by ZhouYe890** [comment]
Firstly, I am glad to receive your reply. When I was adding data, I found that data can only be added in the form of one key value pair per row, as shown in the following situation:
NodeOne:
     - key: a
       desc: b
       class: c
       number: d
     - key: e
       desc: f
       class: g
       number: h
     - key: i
       desc: j
       class: k
       number: l
   If the data volume is large, it will inevitably increase the number of lines in the configuration file. If data can be added as follows, it will inevitably make the entire file structure clearer.
NodeOne:
     - {key: a, desc: b, class: c, number: d}
     - {key: e, desc: f, class: g, number: h}
     - {key: i, desc: j, class: k, number: l}

**Comment by biojppm** [comment]
Use the emit overloads [that accept `FILE*`](https://github.com/biojppm/rapidyaml/blob/9fd8555ce44a9631827112c54b7daf5ad66ddd24/src/c4/yml/emit.hpp#L135) or the ones [that accept streams](https://github.com/biojppm/rapidyaml/blob/9fd8555ce44a9631827112c54b7daf5ad66ddd24/src/c4/yml/emit.hpp#L135).

**Comment by ZhouYe890** [comment]
I tried it today, and the content of the original file is
NodeOne:
- {key: a, desc: b, class: c, number: d}
- {key: e, desc: f, class: g, number: h}
- {key: i, desc: j, class: k, number: l}
Obtained after opening and saving
NodeOne:
- key: a
  desc: b
  class: c
  number: d
- key: e
  desc: f
  class: g
  number: h
- key: i
  desc: j
  class: k
  number: l
The code is as follows
    ::FILE *fp = ::fopen(strFileName.c_str(), "r+");
    size_t n_number = ryml::emit_yaml(tree1, fp);
    ::fclose(fp);
May I ask how I can save the file in its original style. Thank you for taking the time to answer my question.

**Comment by biojppm** [comment]
The parser does not retain the styles when parsing. That feature will eventually be implemented.

But for now, you have to explicitly mark the nodes with the style you want.

**Comment by ZhouYe890** [comment]
Okay, thank you for your reply.
