### ISSUE TITLE
Issue with empty keys

### ISSUE THREAD

**Issue by Mr-S-Mirzoev** [biojppm/rapidyaml#373]
Unlike in most other parsers, empty keys are not supported by ryml.

It is a strange case, but unfortunately, it appeared helpful in one of our company's endeavours.

```yaml
%YAML 1.2
---
m:
  "": ""
```
<img width="1680" alt="image" src="https://github.com/biojppm/rapidyaml/assets/61053551/67c4de64-a309-4f87-a841-85ed277d611e">

**Comment by biojppm** [comment]
Thanks for reporting.

For the record, empty keys *are* supported: all of `{"", ""}`, `"": ""` and `{m: {"":""}}` are parsed correctly (and notice the latter is the flow-style equivalent of your example) .

Instead, what you are seeing is a parse failure . Allow some time for investigating and fixing.
