### ISSUE TITLE
How to serialize subtree as string?

### ISSUE THREAD

**Issue by Jakz** [biojppm/rapidyaml#388]
I have a yml file parsed to a ryml::Tree and I would like to serialize back a subtree to a string but it's not clear how I'm supposed to do.

I tried with:

```
ryml::Tree* srcTree = _node.tree();
ryml::Tree dest;
dest.duplicate_children(srcTree, _node.id(), dest.root_id(), ryml::NONE);

std::string out;
ryml::emitrs(dest, &out);
```

But it's emitting an empty string, possibly I'm missing something from documentation?

**Comment by biojppm** [comment]
To emit a node, just call `emitrs(node, &out)`, or `std::string out = emitrs<std::string>(node)`.

That's it.

I'm assuming the call to `.duplicate_children()` is not relevant to your difficulty (it may be that the resulting tree is invalid).

**Comment by biojppm** [comment]
To be clear, there is no need to duplicate the subtree to be able to emit it.

Just emit the node you want. You can do it with a `ConstNodeRef` (ie `emitrs_yaml(node, &out)`), or with a tree and id (ie `emitrs_yaml(tree, id, &out)`). 

[There is an example on the quickstart](https://github.com/biojppm/rapidyaml/blob/2cf09b073db1921938f7db87cb74560512829f55/samples/quickstart.cpp#L3389).

**Comment by biojppm** [comment]
@Jakz were you able to solve your issue?

**Comment by biojppm** [comment]
ok, closing now. If you have difficulties with the duplicate, let's track that in a different issue.
