### ISSUE TITLE
Is scientific notation number supported?

### ISSUE THREAD

**Issue by Huweicai** [biojppm/rapidyaml#390]
It seems that the number in scientific notation will be recognized as string now:
```c++
int main() {
    const std::string yml_buf = R"(quntity: 9.5e7
quntity2: 95000000)";
    ryml::Tree tree = ryml::parse_in_arena(c4::to_csubstr(yml_buf));
    std::string str_result = ryml::emitrs_json<std::string>(tree);
    std::cout << str_result;
}
```
Output: `{"quntity": "9.5e7","quntity2": 95000000}`

**Comment by biojppm** [comment]
Sorry for the late reply. This is indeed a problem with the way the json emitter detects a number, thanks for reporting.
