### ISSUE TITLE
Build system macro complaints

### ISSUE THREAD

**Issue by sherief** [biojppm/rapidyaml#4]
A strict build system complains about macros like "_C4_foo" since according to the C++ standard:
"identifiers beginning with an underscore followed immediately by an uppercase letter [are implementation reserved]".

**Comment by biojppm** [comment]
Yes, I know, I like to use those macros on my own code, but here that should not happen. I'll eventually get to that.

BTW what is the flag you're using to get these warnings? My tests are run (IIRC) in pedantic + strict + -Werror mode, but I still do not get those warnings. For now, I can pragma disable these warnings (just let me know the flag).

**Comment by biojppm** [comment]
Hey @sherief,

Regarding this problem, I fail to see it on any compiler combination in the CI. In the meantime, the flags were made even more demanding and I have yet to see any warning from this. Can you show me an example where you see a warning triggered by the underscore?
