### ISSUE TITLE
Publish support for more platforms to Conan Central

### ISSUE THREAD

**Issue by mcandre** [biojppm/rapidyaml#401]
Hi,

I am enjoying using the rapidyaml library to help my C++ applications safely load YAML configuration files. However, I would like to port my applications to more diverse platforms, such as MIPS. I see that the Conan Central registry appears to be limited mainly to x86_64 and arm (64) for this package. Given that cross compilation toolchains exist for many more architectures and operating systems, can we please expand the Conan artifacts to feature more platforms?

For example, would be nice to see musl/Linux, MIPS Linux, m68k Linux, FreeBSD, NetBSD, and OpenBSD ports.

**Comment by biojppm** [comment]
Thanks!

The conan recipe is maintained downstream, and I am not involved with it. You should contact the authors of the recipe to address this issue.

**Comment by biojppm** [comment]
Related: https://github.com/biojppm/rapidyaml/pull/637, https://github.com/biojppm/c4core/pull/170, https://github.com/conan-io/conan-center-index/pull/30470
