### ISSUE TITLE
[Feature Request] Add an option to support customize installation

### ISSUE THREAD

**Issue by Runner-2019** [biojppm/rapidyaml#403]
Thx for the wonderful ryml!
Recently, I integrated ryml into my company's projects.It works well, however when I use CPack packaging our project, ryml is always packaged into the final product. We want the packaging to be as lean as possible. Could you help add a custom option that allows users to choose not to install ryml？(If you think this option is necessary but don't have the time, I I would also be happy to pull a merge request if you don't mind.)

e.g. yaml-cpp has [YAML_CPP_INSTALL](https://github.com/jbeder/yaml-cpp/blob/master/CMakeLists.txt#L27) option to help users ignore it's installation.

**Comment by biojppm** [comment]
Thanks!

Sure, that's definitely useful and a pull request would be very welcome.

**Comment by biojppm** [comment]
This was already merged. Closing now.
