### ISSUE TITLE
Rapidyaml calls abort(3) on random input

### ISSUE THREAD

**Issue by gczuczy** [biojppm/rapidyaml#404]
Hello,

I would like to ask, how are we supposed to get parse errors, when the lib calls abort(3) here? https://github.com/biojppm/rapidyaml/blob/8c1d6221dea11259bd63b9fadb081002fe064766/src/c4/yml/common.cpp#L42

The stack using the libs can gracefully handle this, however when the underlying lib is calling abort(3), it'll just case whole stack to error out, killing the possibility of graceful error handling.

Could you please add a snippet to the example snippets on how to gracefully handle such errors? An example would be feeding 32 bytes of random binary data to the lib, and catching the error.

**Comment by biojppm** [comment]
A note that should be there (and maybe a separate example is that the error callback mechanism in ryml works also with `setjmp()`/`longjmp()`.

**Comment by biojppm** [comment]
Now that I am addressing #389, I wonder if that was the problem you were seeing?
