### ISSUE TITLE
An incomprehensible behavior occurred while using the for loop

### ISSUE THREAD

**Issue by pengwzhou** [biojppm/rapidyaml#408]
Hi author, I want to create multiple nodes in a for loop, but only the last node is saved in root. Can you tell me why？
```c++
ryml::Tree tree;
  ryml::NodeRef root = tree.rootref();
  root |= ryml::MAP; // mark root as a map
  for (int i = 0; i < 10; ++i) {
    char buf_[10];
    ryml::csubstr result = ryml::cat_sub(buf_, "cam", i);
    ryml::NodeRef int2 = root[result];
    int2 |= ryml::MAP;
    int2["camera_model"] << "pinhole";
    int2["test_length"] << i;
  }

  std::string str_result = ryml::emitrs_yaml<std::string>(tree);
  std::cout << str_result << std::endl;
```
Output:
```c++
cam9:
  camera_model: pinhole
  test_length: 9
```

**Comment by biojppm** [comment]
There is a serious error in your code: you are making the keys point at dangling memory. 
If you want to create the keys on the go, you need to make sure that all of the keys continue to exist with the tree.

One possible solution for ensuring the keys do not dangle is this, which uses the tree's arena:
```c++
for (... i) {
   size_t required_size = cat({}, "cam", i); // do a blank run to find the required size
   substr keybuf = tree.alloc_arena(required_size);
   csubstr key = cat_sub(keybuf, "cam", i);
   assert(key.len == keybuf.len);
   NodeRef int2 = root[key];
   ...
}
```
Or alternatively, if the number of nodes is small, it is simpler to pick a safe max size:
```c++
for (... i) {
   substr keybuf = tree.alloc_arena(10); // just overallocate
   csubstr key = cat_sub(keybuf, "cam", i);
   assert(key.len <= keybuf.len);
   NodeRef int2 = root[key];
   ...
}
```
What happens after you fix the dangling problem?

**Comment by pengwzhou** [comment]
@biojppm Thank you for your help, I understand the suggestions you provided above, and now the code is working properly.
