### ISSUE TITLE
CMake build fail

### ISSUE THREAD

**Issue by cburgard** [biojppm/rapidyaml#42]
The current master of rapidyaml/c4core does not build out-of-the-box.

```CMake Error at ext/c4core/cmake/c4Project.cmake:560 (add_subdirectory):
  add_subdirectory given source "/c4core" which is not an existing directory.
Call Stack (most recent call first):
  ext/c4core/cmake/c4Project.cmake:541 (c4_add_subproj)
  CMakeLists.txt:22 (c4_require_subproject)


-- ryml: -----> target ryml PUBLIC incorporating lib c4core
CMake Error at ext/c4core/cmake/c4Project.cmake:291 (get_target_property):
  get_target_property() called with non-existent target "c4core".
Call Stack (most recent call first):
  ext/c4core/cmake/c4Project.cmake:313 (_c4_get_tgt_prop)
  ext/c4core/cmake/c4Project.cmake:279 (_c4_append_tgt_prop)
  ext/c4core/cmake/c4Project.cmake:1051 (c4_append_target_prop)
  ext/c4core/cmake/c4Project.cmake:1034 (_c4_incorporate_lib)
  ext/c4core/cmake/c4Project.cmake:951 (_c4_link_with_libs)
  ext/c4core/cmake/c4Project.cmake:802 (c4_add_target)
  CMakeLists.txt:25 (c4_add_library)


CMake Error at CMakeLists.txt:101 (c4_add_dev_targets):
  Unknown CMake command "c4_add_dev_targets".
```
I suppose that there's a problem with the `RYML_EXT_DIR` variable, which seems to be unset by default. However, even when setting it, I end up with 

```CMake Error at ext/c4core/CMakeLists.txt:77 (c4_add_dev_targets):
  Unknown CMake command "c4_add_dev_targets".
```
Any suggestions?

**Comment by biojppm** [comment]
Hi @cburgard ! Definitely a bug. Thanks for the heads up; allow me some time to investigate.

**Comment by biojppm** [comment]
By the way - are the submodules up to date? There were changes in c4core and c4core/cmake and they should be in master. So does git status show a clean tree, with up-to-date submodules?

**Comment by biojppm** [comment]
Not able to reproduce - I just successfully built a fresh clone. What does your git status show?

**Comment by cburgard** [comment]
Hi!
Sorry for the late reply. I found my mistake, I didn't realize that "cmake" inside "c4core" is a separate package that needs to be updated separately. While I do see that it's nice to have every component factored out as a separate package, having these stacks of subpackages is a bit tedious to keep track of :-/
Thanks for investigating though!
