### ISSUE TITLE
[Bug] Text data with commas is incorrectly split

### ISSUE THREAD

**Issue by sides-flow** [biojppm/rapidyaml#422]
I encountered an incorrect output with this data:
```
hello world, whats up?
it's a me, mario, 
bla,
asd
```
I expected the output to return the entire input as one value (just like all the other parsers do), instead of splitting it to multiple values using the commas.

https://play.yaml.io/main/parser?input=aGVsbG8gd29ybGQsIHdoYXRzIHVwPwppdCdzIGEgbWUsIG1hcmlvLCAKYmxhLAphc2Q=
![image](https://github.com/biojppm/rapidyaml/assets/88621685/67fdf203-f206-404e-a650-a9e9dd0f576c)

**Comment by biojppm** [comment]
Thanks for reporting, and the playground link is always nice. 

The parser has been rewritten since, and this has been fixed in the new parser (see #414). I just added tests to confirm this case.

That PR should be merged in a few weeks.

**Comment by sides-flow** [comment]
> Thanks for reporting, and the playground link is always nice.
> 
> The parser has been rewritten since, and this issue has been fixed in the new parser (see #414). I just added tests to confirm this case.
> 
> That PR should be merged in a few weeks.

Great, Looking forward for the next release! Thank you!

**Comment by sides-flow** [comment]
@biojppm Sorry to bump this, but do you have an estimate when a tag will be released for the new parser?
I don't want to change my code according to the new parser's API and rewrite it afterwards in case changes will happen...
Thanks!

**Comment by biojppm** [comment]
The new build is coming in a couple of weeks. Before making the release, I'm fuzzing the library to harden it, and this has revealed a handful of bugs that need fixing. So it may be a few days, or it may be 2 or 3 weeks.

In any case, you're pretty safe with changes: differences from the previous tag are limited, and it is highly unlikely that there will be further differences before the release. Unless you're doing special calls for parsing, it is likely that you don't have to change your code at all regardless of which release. And if you do, they will be limited. My advice is to do the jump now. Have a look at the current changelog and consider this.
