### ISSUE TITLE
Serialize std::filesystem::path error

### ISSUE THREAD

**Issue by Siltnamis** [biojppm/rapidyaml#424]
Hi how to correctly supply `to_chars` overload for `std::filesystem::path`?
All my other custom types work by overloading `write` or `to_chars` but with filesystem::path I always get a compile error which says that it somehow does not find a matching function. What am I doing wrong?

```c++
#include <filesystem>

#define RYML_SINGLE_HDR_DEFINE_NOW
#include "rapidyaml.hpp"

size_t to_chars(ryml::substr buf, std::filesystem::path const& p) { 
	return to_chars(buf, p.generic_string());
}

int main(int argc, char** argv)
{
	std::filesystem::path path = "C:/sample";
	ryml::Tree tree{};
	ryml::NodeRef root = tree.rootref();
	root << path;
	return 0;
}
```
```
./rapidyaml.hpp:19835:22: error: no matching function for call to 'to_chars'
 19835 |         size_t num = to_chars(rem, a);
       |                      ^~~~~~~~
./rapidyaml.hpp:21107:29: note: in instantiation of function template specialization 'c4::yml::Tree::to_arena<std::filesystem::path>' requested here
 21107 |         csubstr s = m_tree->to_arena(v);
       |                             ^
./rapidyaml.hpp:21561:8: note: in instantiation of function template specialization 'c4::yml::NodeRef::set_val_serialized<std::filesystem::path>' requested here
 21561 |     n->set_val_serialized(v);
       |        ^
./rapidyaml.hpp:21233:9: note: in instantiation of function template specialization 'c4::yml::write<std::filesystem::path>' requested here
 21233 |         write(this, v);
       |         ^
main.cpp:22:7: note: in instantiation of function template specialization 'c4::yml::NodeRef::operator<<<std::filesystem::path>' requested here
   22 |         root << path;
   ```

**Comment by biojppm** [comment]
Try putting the prototype before the `#include rapidyaml`. This is explained in the quickstart.

**Comment by Siltnamis** [comment]
I am a bit confused on how to declare that function before `#include <rapidyaml.hpp>` if the function requires `ryml::substr` as a parameter and I cannot really forward declare it? I am using the single header variant of the library.

**Comment by biojppm** [comment]
Good point. This was conceived before setting up the single header, and you've just caught a rough edge.

In this case, one solution would be to explicitly provide the forward declarations before the function, including that of the facilities used inside the function.

Perhaps an easier solution would be to include the single header in declaration mode, then define your function, and then include the single header in definition mode.

Let me know if it works for you.

**Comment by Siltnamis** [comment]
Including the library in declaration mode, declaring my overload and then including the library in definition mode gave me the same result.

If I understand things correctly I should be able to overload just the `write` function and since it takes node as a pointer it can be forward declared. But doing something like that also doesn't work for me:
```c++
#include <filesystem>

namespace c4 { namespace yml { class NodeRef; } }
namespace ryml { using namespace c4::yml; using namespace c4; }
void write(ryml::NodeRef* n, const std::filesystem::path& p);

#define RYML_SINGLE_HDR_DEFINE_NOW
#include "rapidyaml.hpp"

void write(ryml::NodeRef* n, const std::filesystem::path& p)
{
	write(n, p.generic_string());
}
```

But what actually confuses me the most is that all my other custom types work just fine. I would expect it to not work for them as well if it is a requirement to declare these overloads before including the library.

The only hacky workaround I found so far was to directly add this function inside the rapidyaml.hpp header near the string specialization.

**Comment by biojppm** [comment]
> But what actually confuses me the most is that all my other custom types work just fine. I would expect it to not work for them as well if it is a requirement to declare these overloads before including the library.

That's relevant and suggests that something special is going on with the fs path type. I'm going to have a look.

**Comment by biojppm** [comment]
Actually, you are including `rapidyaml.hpp`. This is *not* the single header; it is the umbrella header bringing in other headers. I changed it to `ryml_all.hpp` and it just works, regardless of include order.

To be clear, this full code works:
```c++
// Notice that both types are defined after the ryml include.

#define RYML_SINGLE_HDR_DEFINE_NOW
#include "ryml_all.hpp"

struct vec2 { int x, y; };
size_t to_chars(ryml::substr buf, vec2 v) { return ryml::format(buf, "({},{})", v.x, v.y); }

#include <filesystem>
size_t to_chars(ryml::substr buf, std::filesystem::path const& p) {
	return to_chars(buf, p.generic_string());
}

#include <iostream>
int main(int argc, char** argv)
{
	ryml::Tree tree{};
	ryml::NodeRef root = tree.rootref();
	root |= ryml::SEQ;
	root[0] << std::filesystem::path{"C:/sample"};
	root[1] << vec2{2,3};
	std::cout << root;
	return 0;
}
```


This also works:
```c++
// notice the types are defined before the ryml_all include.

struct vec2 { int x, y; };
size_t to_chars(ryml::substr buf, vec2 v) { return ryml::format(buf, "({},{})", v.x, v.y); }

#include <filesystem>

#define RYML_SINGLE_HDR_DEFINE_NOW
#include "ryml_all.hpp"

size_t to_chars(ryml::substr buf, std::filesystem::path const& p) {
	return to_chars(buf, p.generic_string());
}

// ... etc, as before
```

**Comment by Siltnamis** [comment]
I used the file from releases rapidyaml-0.5.0.hpp ( https://github.com/biojppm/rapidyaml/releases/download/v0.5.0/rapidyaml-0.5.0.hpp ) and renamed it to rapidyaml.hpp. I assumed it was the single header release.
I will try to generate the ryml_all.hpp locally

**Comment by biojppm** [comment]
Actually, the second sample is wrong as I pasted it, sorry.

See the correct forms below, which work even with the header from the release:

```c++
#define RYML_SINGLE_HDR_DEFINE_NOW
#include "./rapidyaml-0.5.0.hpp"  // freshly downloaded from the release

#include <filesystem> // include after

struct vec2 { int x, y; };
size_t to_chars(ryml::substr buf, vec2 v) { return ryml::format(buf, "({},{})", v.x, v.y); }

size_t to_chars(ryml::substr buf, std::filesystem::path const& p) {
	return to_chars(buf, p.generic_string());
}

// ... etc as before
```
and this also works:
```c++
#include <filesystem> // include before

#define RYML_SINGLE_HDR_DEFINE_NOW
#include "./rapidyaml-0.5.0.hpp"  // freshly downloaded from the release

struct vec2 { int x, y; };
size_t to_chars(ryml::substr buf, vec2 v) { return ryml::format(buf, "({},{})", v.x, v.y); }

size_t to_chars(ryml::substr buf, std::filesystem::path const& p) {
	return to_chars(buf, p.generic_string());
}

// ... etc as before
```

Which compiler are you using? I've tried with both clang16 and gcc13.2.

**Comment by Siltnamis** [comment]
I've tried with clang version 17.0.6 and with visual studio 2022 (cl 19.39.33523). Both on windows.
Tried different standards 17/20/23 and getting the same error.

**Comment by Siltnamis** [comment]
Just tried on my raspberry with gcc8.3.0 and it worked perfectly

**Comment by biojppm** [comment]
I suspect some difference within the standard library headers is triggering this behavior.

**Comment by biojppm** [comment]
By the way, did you try both forms?

**Comment by Siltnamis** [comment]
Yes I've tried both:
>See the correct forms below, which work even with the header from the release:

and

>and this also works:

**Comment by Siltnamis** [comment]
Yes I think it makes sense to add fs::path with other provided overloads the only question would be which format to choose. Keep backslashes on windows or convert to forward slashes with `generic_string()`.

Anyway, I've added a few lines inside the header and it works for me as a workaround for now. 
The library overall is really pleasant to use btw!

**Comment by biojppm** [comment]
Finally found what's wrong: [ADL](https://en.cppreference.com/w/cpp/language/adl) (AKA Koenig lookup) fails because of a missing namespace.

You need to declare the `to_chars()` overload in one of the namespaces: either `std::filesystem` or `c4` or `c4::yml`.

So this will work:
```c++
#define RYML_SINGLE_HDR_DEFINE_NOW
#include "./rapidyaml-0.5.0.hpp"  // freshly downloaded from the release

struct vec2 { int x, y; };
size_t to_chars(ryml::substr buf, vec2 v) { return ryml::format(buf, "({},{})", v.x, v.y); }

#include <filesystem> // can be included also before the ryml header

namespace std::filesystem {
size_t to_chars(ryml::substr buf, std::filesystem::path const& p) { return to_chars(buf, p.generic_string()); }
}

#include <iostream>
int main(int argc, char** argv)
{
	ryml::Tree tree{};
	ryml::NodeRef root = tree.rootref();
	root |= ryml::SEQ;
	root[0] << std::filesystem::path{"C:/sample"};
	root[1] << vec2{2,3};
	std::cout << root;
	return 0;
}
```

and this as well:

```c++
// ...

namespace c4 {
size_t to_chars(ryml::substr buf, std::filesystem::path const& p) { return to_chars(buf, p.generic_string()); }
}

// ...
```

... and this as well:
```c++
// ...

namespace c4::yml {
size_t to_chars(ryml::substr buf, std::filesystem::path const& p) { return to_chars(buf, p.generic_string()); }
}

// ...
```
I've had to face this problem several times before. This time I forgot all about it, apparently... Also, if you look for example [at the `to_chars()` implementation for `std::string`](https://github.com/biojppm/c4core/blob/98f783e462daddfe8b12ea2741515315fb1c44af/src/c4/std/string.hpp), you'll notice that `to_chars()` is under `c4`. That is the hint on how to do it.

So **you can use the clean version of the header, provided you define `to_chars()` in one of the three namespaces above.**

Note that unfortunately you cannot use `ryml`, because [`ryml` is an importing namespace for `c4::yml`](https://github.com/biojppm/rapidyaml/blob/master/src/ryml.hpp):
```c++
// ...

namespace ryml { // error, sorry! ryml is merely an importing namespace for c4::yml
size_t to_chars(ryml::substr buf, std::filesystem::path const& p) { return to_chars(buf, p.generic_string()); }
}

// ...
```

As for adding `std::filesystem::path` to the library's default std helpers, that's unfortunately not possible because of the generic vs native question. If it were added, one of the two would be have to be forced on the users, and that's not a legitimate thing for a library like this.

Also, let me point out that if the reason you're using `std::filesystem::path` is merely for path manipulation, it may be that you can just use the `csubstr` class, which provides [Path-like manipulation methods](https://rapidyaml.readthedocs.io/latest/doxygen/structc4_1_1basic__substring.html) (search for Path-like in that link), and spares you the inherent allocation in `p.generic_string()`.
