### ISSUE TITLE
convenience helpers for `std::vector`

### ISSUE THREAD

**Issue by cburgard** [biojppm/rapidyaml#44]
I've found it a bit cumbersome to read/write `std::vector`s of things that already support a `<<` and `>>` operator, hence I came up with these helpers for my own purposes (not very efficient coding on my side, but you get the message):

```
template<class T> void read(NodeRef const& n, std::vector<T> *v){
  for(size_t i=0; i<n.num_children(); ++i){
    T e;
    n[i]>>e;
    v->push_back(e);
  }
}

template<class T> void write(NodeRef *n, std::vector<T> const& v){
  *n |= c4::yml::SEQ;
  for(auto e:v){
    n->append_child() << e;
  }
}
```
Any chance of adding them to `node.hpp`, or are there reservations against including `vector`?

**Comment by biojppm** [comment]
[This is already covered in the main README](https://github.com/biojppm/rapidyaml#stl-interoperation).

Indeed, there is a policy of not bringing in STL containers into ryml itself, but there exist opt-in headers for `std::vector`, `std::map` and `std::string`;  you only need to include them, eg `#include <ryml/std/vector.hpp>` just for vector or `#include <ryml/std/std.hpp>` for everything.
