### ISSUE TITLE
How to not display the internal log like _c4err("parse error");

### ISSUE THREAD

**Issue by yuzu-ogura** [biojppm/rapidyaml#449]
Hello, I have a problem that I'd like to unify the log output, so can I close the internal log of ryml?

**Comment by biojppm** [comment]
That's not an *internal log*; there are no logs coming from the library (and if there are, that's a bug, and I'd like to hear about it).

That is an error being reported by the default error handler; the default error handler prints the error message and calls abort. If you don't want this behavior, you need to set your own error handler. See in the quickstart for several examples on how to do this.

**Comment by yuzu-ogura** [comment]
> That is an error being reported by the default error handler; the default error handler prints the error message and calls abort. If you don't want this behavior, you need to set your own error handler. See in the quickstart for several examples on how to do this.

Thanks your reply, I got it.
