### ISSUE TITLE
Parsing map keys with '?' (explicit key) in event-based parser does not call actually_val_is_first_key_of_new_map_block

### ISSUE THREAD

**Issue by buty4649** [biojppm/rapidyaml#453]
I encountered an issue while using the event-based parser in rapidyaml. When parsing map keys that use the '?' key (explicit key), the function `actually_val_is_first_key_of_new_map_block` is not called.

### Steps to reproduce:

1. I used `tools/ryml-yaml-events` to verify the behavior.
2. To make the output clearer, I applied the patch from [this commit](https://github.com/buty4649/rapidyaml/commit/fb050a27b93b65f5139ab79d70b53e1b8335aca4).

```
$ cat ng.yaml
? {foo: bar}
: hoge
$ ./build/tools/ryml-yaml-events ng.yaml
+STR
+DOC
+MAP
+MAP {}
=VAL :foo
=VAL :bar
-MAP
=VAL :hoge
-MAP
-DOC
-STR
```

When not using the explicit key, `actually_val_is_first_key_of_new_map_block` is called:

```
$ cat ok.yaml
{foo: bar}
: hoge
$ ./build/tools/ryml-yaml-events ok.yaml
+STR
+DOC
+MAP actually_val_is_first_key_of_new_map_block
+MAP {}
=VAL :foo
=VAL :bar
-MAP
=VAL :hoge
-MAP
-DOC
-STR
```

**Comment by biojppm** [comment]
Thanks for reporting! Allow some time to investigate.

**Comment by biojppm** [comment]
There is nothing wrong here, except that 
```yaml
{foo: bar}
: hope
```
is invalid YAML. On the other hand, both `{foo: bar}: hoge` and 
```yaml
? {foo: bar}
: hope
```
are valid, and equivalent.

As for rapidyaml's behavior with the leading `?`,  the question mark enables the parser to enter into a state where it knows any map is a key as soon as it starts, so no later call to `actually_` is needed.

BUT there is an actual problem with rapidyaml in that it tolerates the invalid YAML. It should error out. This issue will track that.

**Comment by buty4649** [comment]
Thank you for the reply, investigation, and for adding the test cases.
I apologize for presenting invalid YAML.
I understand why actually_val_is_first_key_of_new_map_block was not being called.
Upon reviewing the code I wrote, I found a bug.
After fixing the bug, the behavior was as intended.
Therefore, I will close this issue.
