### ISSUE TITLE
Serialize to JSON

### ISSUE THREAD

**Issue by Ambrase** [biojppm/rapidyaml#46]
It seems it is possible to do this, but neither this:
`ryml::Tree tree = ryml::parse(c4::to_csubstr(str.c_str()));`
`std::ostringstream jsonStream;`
`jsonStream << ryml::as_json(node);`

nor this works for me:
`ryml::NodeRef node = tree["parameters"];`
 `std::ostringstream jsonStream;`
 `jsonStream << ryml::as_json(node);`

The first is failing with "_no doc processing for JSON_", the second is with "_expected true: _p(node)->is_map()_".

Am I doing something incorrectly?

Thanks

**Comment by biojppm** [comment]
From the message, it would seem that the YAML you are using is not compatible with the JSON grammar subset. 

But it could also be a different issue; it's hard to tell from the info you provide. Can you also provide a minimum verifiable example that reproduces the errors you're seeing?

**Comment by Ambrase** [comment]
It is because of the "---" start in the initial configuration file. If a Tree is filled with such a file, then the Tree cannot be converted to JSON anymore. If I remove "---", then it is convertible.
So, "---" line could be just removed as a workaround.

**Comment by biojppm** [comment]
Indeed - emitting to JSON requires allows only the JSON-compatible grammar subset of YAML. That's why.

Right, closing this. Feel free to reopen as needed.
