### ISSUE TITLE
GIT TAG v0.7.1 is broken

### ISSUE THREAD

**Issue by marcalff** [biojppm/rapidyaml#468]
According to the release notes:

* ryml 0.7.1 is released (thanks)
* release 0.7.1 contains the fix for issue #455 (more thanks)
  * as a side comment, the PR for the fix is #461 instead of 460 as documented in the release notes. 

However, cloning from tag v0.7.1 and building from source still shows the bug.

By inspecting closely the git history, it turns out:

* The fix is not present in git tag v0.7.1
* The fix is present in branch master
* The tag itself, v0.7.1, does not exist in the git log for branch master, while v0.7.0 is there
* The git tag v0.7.1 points ... elsewhere ?

This URL:

* https://github.com/biojppm/rapidyaml/tree/v0.7.1

displays:

```
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
```

Not even sure how this can happen with git or github.

**Comment by biojppm** [comment]
Thanks. This was a botch of the git tag, which was unnoticed.

I've deleted the tag, and applied the tag again to the right commit for 0.7.1 is 5ccf9a24. (BTW, [the release page](https://github.com/biojppm/rapidyaml/releases/tag/v0.7.1) will always show the commit correctly, even when the tag is wrong.)

FWIW, 0.7.2 is also about to show up.
