### ISSUE TITLE
segfault in destructor of Parser

### ISSUE THREAD

**Issue by cburgard** [biojppm/rapidyaml#47]
Hi!
Not sure if I'm doing anything stupid, but I do get a segfault during the destructor of the parser. It seems to be related to the `m_stack` being `NULL`, but that's about where my understanding stops.

Compile and run with

    g++ -o test test.cpp -DNDEBUG -lryml
    ./test

test.cpp

    #include <sstream>
    #include <iostream>
    #include <fstream>
    
    #include <ryml.hpp>
    #include <c4/yml/std/map.hpp>
    #include <c4/yml/std/string.hpp>
    #include <c4/yml/common.hpp>
    
    size_t count_nlines(c4::csubstr src) {
      // helper function to count the lines
      size_t n = (src.len > 0);
      while(src.len > 0)
        {
          n += (src.begins_with('\n') || src.begins_with('\r'));
            src = src.sub(1);
        }
      return n;
    }
    
    c4::yml::Tree makeTree(std::istream& is){
      if(!is.good()) throw std::runtime_error("invalid input!");
    
      std::cout << "reading string" << std::endl;
      std::string s(std::istreambuf_iterator<char>(is), {});
      auto src = c4::to_csubstr(s.c_str());
      size_t nlines = count_nlines(src);
      std::cout << "creating tree" << std::endl;
      c4::yml::Tree tree(nlines,s.size());
      std::cout << "parsing" << std::endl;
      c4::yml::Parser np;
      np.parse({}, tree.copy_to_arena(src), &tree);
      std::cout << "returning" << std::endl;  
      return tree;
    }
    
    int main(){
      std::ifstream is("myfile.json");
      auto t = makeTree(is);
      std::cout << "all good!" << std::endl;
      return 1;
    }

myfile.json:

    {
        "Gaussian": {
            "class": "RooGaussian",
            "arguments": [
                "x",
                "mean",
                "sigma"
            ]
        },
        "Poisson": {
            "class": "RooPoisson",
            "arguments": [
                "x",
                "mean"
            ]
        },
        "prod": {
            "class": "RooProduct",
            "arguments": [
                "factors"
            ]
        },
        "interpolation0d": {
            "class": "RooStats::HistFactory::FlexibleInterpVar",
            "arguments": [
                "vars",
                "nom",
                "low",
                "high"
            ]
        },
        "sumpdf": {
            "class": "RooRealSumPdf",
            "arguments": [
                "samples",
                "coefficients"
            ]
        },
        "paramhist": {
            "class": "ParamHistFunc",
            "arguments": [
                "observables",
                "parameters"
            ]
        },
        "ARGUS": {
            "class": "RooArgusBG",
            "arguments": [
                "mass",
                "resonance",
                "slope",
                "power"
            ]
        }
    }

**Comment by biojppm** [comment]
thanks for reporting! allow me some time for investigating.

**Comment by cburgard** [comment]
@biojppm : are there any news on this? this is somewhat of a blocker for me.

**Comment by biojppm** [comment]
sorry, I've been really busy these weeks, and haven't looked at this yet.

**Comment by biojppm** [comment]
@cburgard I can't reproduce this; see the commit above with my tries.

Can you make it happen there? If you are able to reproduce it there, I'll pick it up.

**Comment by cburgard** [comment]
Hey. Thanks so much for investigating!
I tried to build with `cmake -DBUILD_SHARED_LIBS=ON -DRYML_BUILD_TESTS=ON` in order to run your test, but I get this: `/usr/bin/ld: libryml-testlib.so: undefined reference to `c4::yml::get_case(c4::basic_substring<char const>)'
`. any thoughts?

**Comment by biojppm** [comment]
There was a problem when building the tests with shared libraries -  this branch (github47) fixes the problem for linux, but windows is still broken. I guess you can try again. Those flags seem right. Also, can you try a static build? Does the problem still occur?

**Comment by cburgard** [comment]
Not sure if we should create a new issue for this by now, but it seems you forgot to push c4core or something like that:

    fatal: remote error: upload-pack: not our ref 7f36ba0ce97c3a21941595912681f2f57104c4ba
    fatal: the remote end hung up unexpectedly
    Fetched in submodule path 'c4core', but it did not contain 7f36ba0ce97c3a21941595912681f2f57104c4ba. Direct fetching of that commit failed.

**Comment by biojppm** [comment]
Any news?

**Comment by cburgard** [comment]
Hi!
Thanks for the ping.
It's interesting (= I don't understand it).
The test case runs without issue as you say. I'd like to test my own script now again (which failed a few days back when I posted the issue), but unfortunately, I can only really do that once I can build with `BUILD_SHARED_LIBS=ON` again..., which still doesn't work (`/usr/bin/ld: libryml-testlib.so: undefined reference to `c4::yml::get_case(c4::basic_substring<char const>)'`)
Do you think you can fix this anytime soon so I can cross-validate with my test case?

**Comment by biojppm** [comment]
Indeed, there was a linker error in one of the tests which did not use the declarative style test cases. You should be able to build now.

On the downside, I did not get this to fail: nor in static nor in dynamic linking version.

**Comment by cburgard** [comment]
Thanks for fixing the linker error.

On the more puzzling side though, the test case you kindly prepared runs without issue, but my MWE still show's the same behavior and I can't figure out what the difference is between them.... ???

Any idea?

**Comment by biojppm** [comment]
I think you could tweak the test until you can get it to crash in a similar way to your MVE. If it is something bad in ryml, then reproducing the crash in the test should be possible.

**Comment by cburgard** [comment]
I was able to resolve the issue now. As it turns out, I had an old version of rapidyaml installed on my machine that the linker was picking instead of the one I was working with. This was also the reason then why it worked with static, but not with dynamic linkage :-)
Very subtle, very annoying. Sorry for stealing your time. Thanks for following through!
