### ISSUE TITLE
Clarification for child access complexity

### ISSUE THREAD

**Issue by Gei0r** [biojppm/rapidyaml#49]
Hi, I need some clarification about the complexity of child lookups (O(1) vs O(n)).

The readme say:

> the complexity of operator[] is linear on the number of children of the node on which it is invoked. 
[...]
> with a node index, a lookup is O(1)

So which one is it?

On a related note, `Tree::lookup_path()` returns a `size_t target`. How can I efficiently get the looked up node?

**Comment by biojppm** [comment]
Basically it boils down to this:
 * hierarchy calls are all O(N) with N the size of the scope at which they apply
 * non-hierarchy calls are all O(1)

Hope this clarifies things. I'll keep this in mind and improve the documentation before closing this issue.

**Comment by Gei0r** [comment]
Thank you.
Maybe you can also clarify the difference between `Tree::_p(size_t i)` and `Tree::operator[](size_t i)`.
The comment claims that `_p()` is "a shorter form of []" (don't see how it's shorter btw), but from reading the code I think that `_p()` is a "non-hierarchy call" and `operator[]()` is a "hierarchy call".
Is that correct? Is `_p()` even meant to be user-callable (the underscore kinda makes it look "private")?

**Comment by biojppm** [comment]
`NodeData * tree._p()` is indeed not meant for clients, as the name implies. The comment there is out of date; but it is the non-checked equivalent of `NodeData * tree.get(size_t)`.

**Comment by biojppm** [comment]
Also, addressing the side comment: in member methods where it's meant to be used, calling `_p(i)` is definitely shorter and easier on the eye than `(*this)[i]`. Of course, it is indeed longer outside of the class as you are/were considering doing.

**Comment by biojppm** [comment]
Feel free to reopen if you have more questions.

**Comment by Gei0r** [comment]
Thank you for clarifying, but the text is incomplete:

> As for `NodeRef`, `NodeRef::operator[]`is linear on the number of children
of the node on which it is invoked. The difference from `NodeRef::operator[]`
and ``

**Comment by biojppm** [comment]
Indeed! Thanks for the heads up.

**Comment by biojppm** [comment]
Again, reopen at will.
