### ISSUE TITLE
Cannot dereference a yaml reference

### ISSUE THREAD

**Issue by sidezrw** [biojppm/rapidyaml#50]
I am trying to parse some yaml files with anchors and references all over, of different types. However, I am unable to get the dereferenced value. Maybe I am doing something wrong, or there is some magic method that will do this for me and I do not know about. How can I dereference a yaml reference without having to traverse the whole yaml tree to find the correct reference?

One of the yaml files I am trying to parse is:

```
collection:
    col_id: &col_id 'col_0'
    col_num: &col_num 3

test:
    id: *col_id
    num: *col_num
```

The sample code to parse it is:

```
#include <iostream>
#include <string>
#include <ryml.hpp>
#include <ryml_std.hpp>

namespace rapidyaml = ryml;

int main()
{
        std::string s =
R"(
collection:
    col_id: &col_id 'col_0'
    col_num: &col_num 3

test:
    id: *col_id
    num: *col_num
)";
        rapidyaml::Tree yaml = rapidyaml::parse(c4::to_csubstr(s));
        std::cout << yaml << std::endl;

        std::string collection_id;
        int collection_num;
        std::string test_id;
        int test_num;

        yaml["collection"]["col_id"] >> collection_id;
        std::cout << collection_id << std::endl;
        std::cout << yaml["collection"]["col_id"].val() << std::endl;
        std::cout << std::endl;

        yaml["collection"]["col_num"] >> collection_num;
        std::cout << collection_num << std::endl;
        std::cout << yaml["collection"]["col_num"].val() << std::endl;
        std::cout << std::endl;

        yaml["test"]["id"] >> test_id; // expected 'col_0' obtained '*col_id'
        std::cout << test_id << std::endl;
        std::cout << yaml["test"]["id"].val() << std::endl;
        std::cout << yaml["test"]["id"].val_ref() << std::endl; // expected, maybe, 'col_0' obtained 'col_id'
        std::cout << std::endl;

        yaml["test"]["num"] >> test_num; // assertion failed, but int(3) expected
        std::cout << test_num << std::endl;
        std::cout << yaml["test"]["num"].val() << std::endl;
        std::cout << yaml["test"]["num"].val_ref() << std::endl;
        std::cout << std::endl;

        return 0;
}
```

**Comment by biojppm** [comment]
Dereferencing is opt-in; after parsing, you have to call yaml.resolve() explicitly if you want resolved references in the tree. This method will resolve all references and substitute the anchored values in place of the reference.

The resolve() method first does a full traverse of the tree to gather all anchors and references in a separate collection, then it goes through that collection to locate the names, which it does by obeying the standard diktat that 
> an alias node refers to the most recent node in the serialization having the specified anchor

So, depending on the number of anchor/alias nodes, this is a potentially expensive operation, with a best-case linear complexity (from the initial traversal). This potential cost is the reason for requiring an explicit call.

Let me know if this works for you or if there is something else that got lost in translation.

And thank you for reporting. This will be added to the documentation and README; it is something that should be clearer than it is.
