### ISSUE TITLE
include could not find load file: ..../c4Project.cmake

### ISSUE THREAD

**Issue by hihihlo** [biojppm/rapidyaml#53]
i am new user at cmake,  
i want to build a .lib for Visual Studio 2015 in windows,
when i run :
`cmake -S source_dir -B build_dir -DCMAKE_INSTALL_PREFIX=install_dir`

it final show error :
`CMake Error at CMakeLists.txt:4 (include):`
`  include could not find load file:`
`    ./ext/c4core/cmake/c4Project.cmake`
` `
`CMake Error at CMakeLists.txt:6 (c4_declare_project):`
`  Unknown CMake command "c4_declare_project".`

how to build and copy c4core, for c4core can incorporated into ryml ?
need help, thank you ~

**Comment by biojppm** [comment]
Your submodules are not checked out.

See this: https://github.com/biojppm/rapidyaml#installing-and-using . Take care to use the `--recursive` flag to force git to clone the submodules as well.

If you omit --recursive, you will have to do `git submodule init` and `git submodule update` after the clone

**Comment by hihihlo** [comment]
You are right, thank you very much.
First time I pressed "Clone or download" button in Web-Browser, and unpack it.
This time I use git command as you said, it work fine -- thanks !!

**Comment by biojppm** [comment]
That's alright! Keep up the good work.
