### ISSUE TITLE
parse error when have space(s) BEFORE colon (':') char

### ISSUE THREAD

**Issue by hihihlo** [biojppm/rapidyaml#54]
if have space BEFORE colon, ex:
```
keyA :
    keyB : test value
```
the ryml::parse() will fail, but I saw many web/valid_tools allow the formatting :
    * example data  :    https://yaml.org/start.html
    * JS-YAML demo. YAML JavaScript parser : http://nodeca.github.io/js-yaml/
    * Online YAML Parser : http://yaml-online-parser.appspot.com/
    * Minify YAML - Online YAML Tools : https://onlineyamltools.com/minify-yaml

I don't know which one is correct,
or could you provide a options to decide ?

**Comment by biojppm** [comment]
Let me investigate. Please be aware that I'm taken up and it may take me a while to do this.

**Comment by hihihlo** [comment]
it really work now !
thank you for fix it quickly ~

**Comment by biojppm** [comment]
Reopening from #65.
