### ISSUE TITLE
ryml::parse complains about ambiguous call, reading file

### ISSUE THREAD

**Issue by Merkaber** [biojppm/rapidyaml#57]
Trying to use your example, I receive the following error:

"call of overloaded 'parse(char [7])' is ambiguous"

`    char str[] = "{test}";`
`    ryml::Tree tree = ryml::parse(str);`

I also tried loading a file:

`    std::ifstream in(path);`
`    std::string contents((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());`
`    char* s = &contents[0];`
`    ryml::Tree tree = ryml::parse(s);`

But parse does not accept one argument.

Do you have an easy example for loading a large file (75,6 mb) including UTF-8 characters and iterate over it? yaml-cpp takes like 10+ seconds to read the file.

**Comment by biojppm** [comment]
You've caught an outdated doc - sorry. Here's the explanation.

The ambiguity you are seeing is intentional. Consider this:
```c++
using namespace ryml;
char str[] = "{a: 1}"; // a mutable buffer
substr rw = str; // ok: create a mutable view to the buffer
csubstr ro = str; // ok: it's legal to have a mutable buffer, but not want to mutate it
```
When the buffer is immutable, you can only create immutable views:
```c++
const char str[] = "{a: 1}"; // an immutable buffer
substr rw = str; // ERROR: won't compile: cannot mutate immutable memory
csubstr ro = str; // ok
```
Now, there are two overload candidates for your call:
```c++
Tree parse(substr rw);  // parse in place
Tree parse(csubstr ro);  // copy to the tree's arena and parse there
```
So, given the above, you have:
```c++
Tree t;
const char r[] = "{a: 1}";
t = parse(r); // no ambiguity: creates a csubstr, so copy-and-parse

char s[] = "{a: 2}";
t = parse(s); // error: ambiguous: can be either substr or csubstr
t = parse(to_substr(s)); // disambiguate: parse in place
t = parse(to_csubstr(s)); // disambiguate: copy-and-parse
```
Hope this clears the ambiguity confusion; I'll update the docs to reflect this.

I've just realized that ryml will fail to parse your `{test}` example and any other set. I'm going to open a separate bug to track that problem.

**Comment by biojppm** [comment]
I'm also very interested in your 75MB case. Other than the ambiguity you've seen (and the bug with the sets), ryml should be able to parse it in any of the ways documented in the README. But I am specifically interested in seeing how good or bad ryml does it. Let me know how it goes.

**Comment by biojppm** [comment]
Feel free to reopen or comment further if there are any questions.

And of course, let me know how well it worked for your large case!
