### ISSUE TITLE
emit json example

### ISSUE THREAD

**Issue by parihaaraka** [biojppm/rapidyaml#72]
could you please explain how to create and emit this kind of json:
`{"1": null}`

**Comment by biojppm** [comment]
How do you build the tree, and what do you get on the output?

**Comment by parihaaraka** [comment]
I build it in accordance with https://github.com/biojppm/rapidyaml#creating-a-tree
But i can get only `{1: ...}` or `{"\"1\"": ...}`.
I haven't tried to get `null` value. Lack of time to dig into sources :/ Just serialize my data manually.

**Comment by biojppm** [comment]
Sorry, that's too vague. What are the exact values that you are setting? Can you provide a minimum verifiable example of your use case?

**Comment by parihaaraka** [comment]
```c++
using namespace c4::yml;
Tree tree;
NodeRef r = tree.rootref();
r |= MAP;
r["1"] = "test1";
r["\"2\""] = "test2";
emit_json(tree);
```
output:
`{1: "test1","\"2\"": "test2"}`

**Comment by biojppm** [comment]
Well, ryml is omitting quotes for numbers when they are used as keys, [and we shouldn't do that](https://dba.stackexchange.com/questions/234394/must-numeric-json-keys-be-quoted). Also, the special strings `null`, `true`, and `false` should not be quoted when used as values, but I think they are.

I'll put in a fix for this.
