### ISSUE TITLE
Parse error with trailing whitespace

### ISSUE THREAD

**Issue by Gei0r** [biojppm/rapidyaml#83]
Hi, it's me again with another whitespace-related parse error 😀 

The following fails to parse (note the two spaces in line 3):

```yaml
a:
  - b
  
c: d
```

Full code:

```c++
#include <ryml.hpp>

int main()
{
    char input[] = "a:\n  - b\n  \nc: d";
    ryml::Tree tree = ryml::parse(c4::substr(input));
}
```
Error message:
```
3:0: (8B):ERROR: ERROR parsing yml: parse error
line 3: '  ' (sz=2)
        ^~~  (cols 0-3)
```

**Comment by biojppm** [comment]
Thanks for reporting. Allow me some time to reproduce, investigate and fix.

**Comment by biojppm** [comment]
I'm hijacking an existing MR with the fix. Hopefully it will be merged this week.
