### ISSUE TITLE
Parsed value of null entries should be null and not ~ (tilde)

### ISSUE THREAD

**Issue by biojppm** [biojppm/rapidyaml#84]
[Details in here](https://github.com/biojppm/rapidyaml/commit/98d3d9763584313a299c2129499d3482b1c933ed#commitcomment-42584617)

**Comment by biojppm** [comment]
@leoetlino The behavior seems correct. Note the commit above, which adds a test proving this.

Indeed this is a change in behavior, but I argue for the better. `{foo: ''}` should not be treated the same as `{foo: }`. The first has an empty string as the value, whereas the second has no value, AKA `~`.

**Comment by biojppm** [comment]
[More info](https://stackoverflow.com/questions/51990175/what-is-the-purpose-of-tilde-character-in-yaml)

**Comment by biojppm** [comment]
But I do recognize that this change in behavior should have been highlighted in the changelog.

**Comment by leoetlino** [comment]
Hmm, I see. This might be a silly question, but how would you distinguish a string that consists of the `~` character and null in this case? (With PyYAML, `{foo: }` gets parsed as `{"foo": None}`, not `""`.) Also, do explicit tags affect this at all?

**Comment by biojppm** [comment]
You are right there - this is ambiguous, and I confess I did not thought of that. It does change the situation. The correct behavior should be for the substr to be `{nullptr, 0}` when null, instead of `"~"`. The tilde should be left for YAML where it's meant to be used.

I'm going to have to reflect on the ramifications and hopefully fix this situation; this bug will track that.
