### ISSUE TITLE
csubstr/substr to std::string using the >> operator

### ISSUE THREAD

**Issue by julianxhokaxhiu** [biojppm/rapidyaml#87]
Hi,

I noticed your awesome library for YAML parsing. I'm very happy with it, and I'd like to thank you a lot for it.

I was trying to play a bit with it, but what I noticed is that I really missed an easy notation to get an `std::string` from a `substr/csubstr`. It would be cool if you could implement an `operator>>` support to write the current `csubstr/substr` content to an `std::string`.

If you could add also support in the `NodeRef` class to dump to an `std::string` when using the `>>` operator, it would be even better.

Thank you in advance if you'll consider this.

**Comment by biojppm** [comment]
The c4core library has the facilities to do that:

```c++
#include <c4/format.hpp>
#include <c4/std/string.hpp>

void basic_approach()
{
   std::string str;
   c4::csubstr ss("the content");
   c4::catrs(&str, ss); // cat + resize
   std::cout << str << "\n;  // the content
}

// so you can provide the operator as you wish
c4::csubstr operator>> (c4::csubstr ss, std::string &str)
{
   c4::catrs(&str, ss); // cat + resize
   return to_csubstr(str); // or you could return the std::string& instead, or not even return
}

void operator_approach()
{
   std::string str;
   c4::csubstr ss("the content");
   ss >> str;
}
```

This is a quick reply off the top of my head, but even if has minor errors it should be enough to get you started.

Let me know if it works for you.

**Comment by biojppm** [comment]
Actually, ignore the `c4::catrs()` approach suggested above; do this instead:

In the `<c4/std/string.hpp>` header you have this, which is even better:

```
/** copy a string view to an existing std::string */
inline bool from_chars(c4::csubstr buf, std::string * s)
{
    s->resize(buf.len);
    C4_ASSERT(!buf.overlaps(to_csubstr(*s)));
    memcpy(&(*s)[0], buf.str, buf.len);
    return true;
}
```

So if you make sure you include this header, even the NodeRef>> should work. See also the relevant README section: https://github.com/biojppm/rapidyaml#stl-interoperation

**Comment by julianxhokaxhiu** [comment]
Hi @biojppm,

thanks for the kind reply! So I actually did follow the instructions in the readme and I've included the headers exactly as you pointed out but it still doesn't work :(

This is a demo example
```cpp
#include <string>
#include <ryml_std.hpp> // include this before any other ryml header
#include <ryml.hpp>
int main()
{
    // ryml can parse in situ (and read-only buffers too):
    char src[] = "{foo: \"bar\"}";
    ryml::substr srcview = src_; // a mutable view to the source buffer
    // there are also overloads for reusing the tree and parser
    ryml::Tree tree = ryml::parse(srcview);

    std::string tmp;
    tree["foo"] >> tmp; // This doesn't seem to work, it says that none of the 16 overloads matches one
}
```

Is there anything I'm currently missing?

Thank you in advance :)

**Comment by biojppm** [comment]
The first statement `tree["foo"] >> tmp` should definitely work given that you are pulling in the std header before. The second statement definitely won't work. If you remove it, you should be good to go.

**Comment by julianxhokaxhiu** [comment]
> The first statement `tree["foo"] >> tmp` should definitely work given that you are pulling in the std header before.

Unfortunately that doesn't seem to work here. I'm using the latest MSVC `16.7.0+b89cb5fde` from VS2019.

**Comment by biojppm** [comment]
It must be something else; I've just made sure this compiles and runs successfully with vs2019:
```c++
#include <ryml_std.hpp>
#include <ryml.hpp>
int main()
{
    auto tree = ryml::parse("foo: bar");
    std::string tmp;
    tree["foo"] >> tmp;
    C4_ASSERT(tmp == "bar");
}
```

**Comment by julianxhokaxhiu** [comment]
Allright, I'll check what's going on here :) Thank you again for at least confirming that it works on your end.

**Comment by biojppm** [comment]
No need to close this yet. Can you provide the compile log for the code above?
