### ISSUE TITLE
rapidyaml ignores global CXX standard and other problems

### ISSUE THREAD

**Issue by stohrendorf** [biojppm/rapidyaml#90]
Version is 0.1.0, included as a git submodule.

## CXX standard override
I have this in my project which works as expected and documented:
```
set( CMAKE_CXX_STANDARD 17 )
set( CMAKE_CXX_STANDARD_REQUIRED ON )
# ... snip ...
add_subdirectory( 3rdparty/rapidyaml )
```

rapidyaml logs the following:
```
-- ryml: using C++ standard: C++11
-- ryml: setting global C++ standard: 11
-- c4core: using C++ standard: C++11
-- c4core: setting global C++ standard: 11
```

That's NOT ok, because I'm relying on c++17. First, there's the non-standard way of setting `CXX_STANDARD` to having use rapidyaml the correct c++ version, second I wouldn't expect a dependency to override my own requirements for a c++ standard, or any other setting required for my project (which still happens when using `CXX_STANDARD`).

## Build & install as internal dependency
Even when using `add_subdirectory( 3rdparty/rapidyaml ryml )` as a command (which is, by the way, also unexpected to explicitly specify a build directory), both `target_link_libraries(foo PRIVATE ryml)` and `target_link_libraries(foo PRIVATE ryml::ryml)` fail, rendering it impossible to use rapidyaml following the instructions in the README. There is of course the possibility to abuse cmake internal variables/intrinsics/etc. to manually patch CMAKE_MODULE_PATH to include the path to the cmake-internal build directory that contains the config so one can use `find_package(...)`, but that's pretty fragile and the behaviour can change between cmake versions without further notice. Have a look at https://github.com/foonathan/type_safe to see how to set up rapidyaml to be used through `add_subdirectory`.

## Dependency on c4
I didn't dig into it too much, but please consider switching to something like https://github.com/gsl-lite/gsl-lite. At least the string handling heavily resembles `string_span`, which is more or less like https://en.cppreference.com/w/cpp/string/basic_string_view. 

## Missing documentation about memory ownership
The documentation is missing the crucial hint about using `node.tree()->copy_to_arena(...)`  when using non-static strings to ensure that these can be properly used with rapidyaml. More generally, please note that rapidyaml is intrinsic and requires all data used within the tree to be either persisted in its own arena or be in static memory, which is crucial when using `set_key`.

## Erroneus handling of value tags
A value tag can only be assigned if the node has a value assigned; this is unexpected, because it requires you to set the tag _after_ setting the value, while yaml itself stores it the other way round. Also, the current version parses `!<...>` up to the next space, not the next `>`. Tag handling also requires the user of the library to explicitly include the leading `!`, which makes it possible to emit invalid yaml.

**Comment by biojppm** [comment]
Thanks for the detailed reporting. The cmake issues seem the most troublesome, so I'm going to look at those first.

**Comment by biojppm** [comment]
In the future, I suggest you log separate issues, making it easier to address them individually.

**Comment by biojppm** [comment]
> The documentation is missing the crucial hint about using node.tree()->copy_to_arena(...) when using non-static strings to ensure that these can be properly used with rapidyaml. More generally, please note that rapidyaml is intrinsic and requires all data used within the tree to be either persisted in its own arena or be in static memory, which is crucial when using set_key.

These two README sections do address the arena behavior:

https://github.com/biojppm/rapidyaml#parsing
https://github.com/biojppm/rapidyaml#creating-a-tree

Also, you mention static memory, but it is not the defining factor. To clarify, if the data lives outside the arena, it does not need to be static memory; *but* just as with `std::string_view` and `gsl::string_span` it does need to be available to the tree at any time it is referenced through the tree, meaning that the data's lifetime must be a superset of the tree's lifetime. static data is a way of achieving that, but not the only one:
```cpp
std::string key = "666", val = "7"; // watchout for lifetime
r.append_child() << 7; // serialize into the arena, point at the resulting serialization
r.append_child() = "7"; // use directly from outside the tree, points at this [static] string
r.append_child() = to_csubstr(val); // use directly from outside the tree, points at this [local] string
                                                       // BEWARE OF LIFETIME

// to serialize keys:
r.append_child() << ryml::key(66) << 7; // serialize key+val into the arena

// use from outside the tree // with static memory
auto ch = r.append_child();
ch.set_key("666");
ch.set_val("7");

// use from outside the tree // with local memory
auto ch = r.append_child();
ch.set_key(to_csubstr(key));
ch.set_val(to_csubstr(val));
```

Does this clarify?

**Comment by biojppm** [comment]
I'm going to track the cmake problems in this issue. The remaining problems you report will have their own issues.

> CXX standard override

There is no override behavior - but ryml is (wrongly) ignoring the global behavior. I've just tried this:

```cmake
cmake_minimum_required(VERSION 3.12)
project(ryml-consumer
        DESCRIPTION "Demonstrates consuming YAML as a subproject"
        HOMEPAGE_URL "https://github.com/biojppm/rapidyaml"
        LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
message(STATUS "CMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}")

add_subdirectory(../../ ryml)
message(STATUS "CMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}")

add_executable(ryml-consumer main.cpp)
target_link_libraries(ryml-consumer ryml)
```
... and this is the output from cmake:
```shell
-- CMAKE_CXX_STANDARD=17                    # <------ value before add_subdirectory()
-- ryml: using C++ standard: C++11
-- ryml: setting global C++ standard: 11
-- ryml: importing subproject c4core (SUBDIRECTORY)... /opt/jpmag/proj/rapidyaml/ext/c4core
-- c4core: using C++ standard: C++11
-- c4core: setting global C++ standard: 11
-- ryml: -----> target ryml PUBLIC incorporating lib c4core
-- CMAKE_CXX_STANDARD=17                    # <------ value after add_subdirectory()
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/jpmag/proj/rapidyaml/examples/importing/build/linux-x86_64-gxx10.2-Debug
```
Notice that the value at top level is still 17 after adding ryml.

There is a problem though, in that ryml is ignoring the original standard - it prints 11 and should print 17. That is a bug indeed.

**Comment by biojppm** [comment]
> Build & install as internal dependency

> Even when using add_subdirectory( 3rdparty/rapidyaml ryml ) as a command (which is, by the way, also unexpected to explicitly specify a build directory), both target_link_libraries(foo PRIVATE ryml) and target_link_libraries(foo PRIVATE ryml::ryml) fail, rendering it impossible to use rapidyaml following the instructions in the README. 

I do not follow. That is not the behavior I'm seeing; the `add_subdirectory()` call in the example I posted above seems to be what you're describing, but it works as intended.

Can you provide a MVE causing the issues you describe?

**Comment by biojppm** [comment]
regarding the ignoring of `CMAKE_CXX_STANDARD` there is a fix and this now [works as expected](https://github.com/biojppm/rapidyaml/runs/1366449111?check_suite_focus=true#step:5:46), so thanks for flagging this.

However, I fail to see the problem you describe with `add_subdirectory()`. [The example I posted](https://github.com/biojppm/rapidyaml/blob/94824286d2a2e2c1a7b62de4d1619c0f0d8ce9e6/examples/add_subdirectory/CMakeLists.txt) is quite similar and works without any issues. Again, can you provide a Minimum Verifiable Example for this issue?

**Comment by stohrendorf** [comment]
Sorry, for the wait. I investigated this and tested the `issue90` branch, and it correctly reports the project-wide C++ standard. Regarding `add_subdirectory`, the problem simply was that I didn't remove the old rapidyaml config referencing the vcpkg installation from `CMakeCache.txt`. So this issue is solved then.
