### ISSUE TITLE
Clarify arena behavior

### ISSUE THREAD

**Issue by biojppm** [biojppm/rapidyaml#91]
_Originally posted by @biojppm in https://github.com/biojppm/rapidyaml/issues/90#issuecomment-723074434_

> The documentation is missing the crucial hint about using node.tree()->copy_to_arena(...) when using non-static strings to ensure that these can be properly used with rapidyaml. More generally, please note that rapidyaml is intrinsic and requires all data used within the tree to be either persisted in its own arena or be in static memory, which is crucial when using set_key.

These two README sections do address the arena behavior:

https://github.com/biojppm/rapidyaml#parsing
https://github.com/biojppm/rapidyaml#creating-a-tree

Also, you mention static memory, but it is not the defining factor. To clarify, if the data lives outside the arena, it does not need to be static memory; *but* just as with `std::string_view` and `gsl::string_span` it does need to be available to the tree at any time it is referenced through the tree, meaning that the data's lifetime must be a superset of the tree's lifetime. static data is a way of achieving that, but not the only one:
```cpp
std::string key = "666", val = "7"; // watchout for lifetime
r.append_child() << 7; // serialize into the arena, point at the resulting serialization
r.append_child() = "7"; // use directly from outside the tree, points at this [static] string
r.append_child() = to_csubstr(val); // use directly from outside the tree, points at this [local] string
                                                       // BEWARE OF LIFETIME

// to serialize keys:
r.append_child() << ryml::key(66) << 7; // serialize key+val into the arena

// use from outside the tree // with static memory
auto ch = r.append_child();
ch.set_key("666");
ch.set_val("7");

// use from outside the tree // with local memory
auto ch = r.append_child();
ch.set_key(to_csubstr(key));
ch.set_val(to_csubstr(val));
```

Does this clarify? @stohrendorf

**Comment by stohrendorf** [comment]
"static memory" was a bit of wrong wording I chose, yet it is "intrusive", although it's only half of the truth (see `<<` vs. `=` for nodes, which is pretty bug-prone). So either you guarantee the data used by the tree has a life-time at least as long as the tree exists, or you put it into its arena. That information is actually a bit too scattered, and there's also no information about how to manually put data into the arena when you don't want to handle lifetime of the data yourself.

**Comment by biojppm** [comment]
I do agree that the `<<` vs `=` difference in behavior is too terse and error prone, and I am not fully satisfied with it. I plan to address that in the near future in an API cleanup to make this difference more evident ([see the ROADMAP](https://github.com/biojppm/rapidyaml/blob/master/ROADMAP.md)).

Regarding the arena behavior...

> there's also no information about how to manually put data into the arena when you don't want to handle lifetime of the data yourself

If you mean adding the data to arena while assigning, then sorry, that's not true; if you search for the word arena in the README, you'll see this `<<` information repeated several times.

> That information is actually a bit too scattered

Maybe you're right here, and maybe that's why you failed to find this information. I'll think of a way to improve that, and will keep this open until it is improved.

**Comment by stohrendorf** [comment]
I'm talking about keys and possibly other stuff here, i.e. `node[node.tree().copy_to_arena(c4::to_csubstr(some_key_var))] << some_value`.

**Comment by biojppm** [comment]
```cpp
// not needed:
node[node.tree().copy_to_arena(c4::to_csubstr(some_key_var))] << some_value;

// does the same - if it doesn't that's a bug and I'd like to hear about it:
node << ryml::key(some_key_var) << some_value;
```
