### ISSUE TITLE
handling of value tags

### ISSUE THREAD

**Issue by biojppm** [biojppm/rapidyaml#92]
_Originally posted by @stohrendorf in https://github.com/biojppm/rapidyaml/issues/90_

> A value tag can only be assigned if the node has a value assigned; this is unexpected, because it requires you to set the tag after setting the value, while yaml itself stores it the other way round. Also, the current version parses !<...> up to the next space, not the next >. Tag handling also requires the user of the library to explicitly include the leading !, which makes it possible to emit invalid yaml.

**Comment by biojppm** [comment]
@stohrendorf -

> Tag handling also requires the user of the library to explicitly include the leading !, which makes it possible to emit invalid yaml

I agree the requirement is somewhat inconvenient. But it is a deliberate design decision, stemming from ryml's memory-view-centric approach.

If ryml accepted tags when the leading `!` is not given by the user, then ryml will have to add it there - first making sure that `!` is serialized into the tree arena, then serializing the tag after it so that it is available as a fully formed valid tag string. In my view, this guaranteed cost (first the branching then maybe the serialization) offers scant benefits -- after all, the `!` is mandated on tags, and users generally must be aware of this.

Having said that, you are correct in the point you make about the possibility of invalid YAML. There should be assertions verifying existence of the leading `!`, and I just checked - there are none. So these assertions need to be added, and this issue will stay open until that's fixed.

Also, this should be made explicit in the documentation.


> A value tag can only be assigned if the node has a value assigned; this is unexpected, because it requires you to set the tag after setting the value, while yaml itself stores it the other way round. 

Yes, I agree. Again, the API needs a cleanup, and issues such as these will be ironed out then. But first I'm focusing on correctness: reading floats and passing the YAML test suite. Then API cleanup and only then the first major release. So have patience in this regard; you can still write your application-level convenience adapters for situations like this.

> the current version parses !<...> up to the next space, not the next >

That could or could not be a bug. I *think* I understand what you mean but I want to be sure. Is the space inside or outside? Can you clarify with an example?

**Comment by stohrendorf** [comment]
I just had a look at the code, and it's handled the same like non-`<>`-enclosed tags, meaning it just assumes the tag ends at the next space. In other words, a value of `!<foo bar> baz` would have the tag `!<foo`. and a payload value of `bar> baz`.

**Comment by stohrendorf** [comment]
Also, about the leading "!": I don't think that character must be stored in the arena at all if you consider everything that follows as the real tag payload, it's just a matter of how to serialize and deserialize it. There's already a check with different behaviours for when tags are present and when they are not when parsing, so it should be easy to just emit a "!" when serializing and to strip off the first "!" when deserializing. This would also make client-side code a bit easier as there would be no need anymore to manually prefix a "!" to every tag when it's a simple one, the other tag types are more complicated and I agree that there's no real point in adding such complex behaviour for handling them.

**Comment by biojppm** [comment]
> I just had a look at the code, and it's handled the same like non-<>-enclosed tags, meaning it just assumes the tag ends at the next space. In other words, a value of !<foo bar> baz would have the tag !<foo. and a payload value of bar> baz.

That is true, but whether or not it is wrong depends on whether tags are allowed to contain spaces. And AFAIK, they are not. Since tags are URIs, then spaces have to be encoded as `%20`. Can you show me an example of a tag with spaces?

**Comment by biojppm** [comment]
> Also, about the leading "!": I don't think that character must be stored in the arena at all if you consider everything that follows as the real tag payload, it's just a matter of how to serialize and deserialize it. There's already a check with different behaviours for when tags are present and when they are not when parsing, so it should be easy to just emit a "!" when serializing and to strip off the first "!" when deserializing.

Fair point, and the balance seems good enough. I will take it up, and this issue will track that.

**Comment by stohrendorf** [comment]
I just had a look at the official YAML 1.2 syntax spec, and I was wrong regarding spaces in tags. But the official spec is `[98] c-verbatim-tag ::= "!" "<" ns-uri-char+ ">"` (`ns-uri-char` not containing spaces), which explicitly states the `>` as the last character of the expression. rapidyaml basically relies on `ns-uri-char` while parsing, not `>`, which I just find a bit confusing.
