### ISSUE TITLE
Release tarballs are missing ext/c4core

### ISSUE THREAD

**Issue by saraedum** [biojppm/rapidyaml#95]
The tarball that's in the Release section does not contain the submodules, i.e., ext/c4core. So I cannot download and cmake it without manually downloading this dependency and putting it there, see e.g., [this build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=245797&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0&l=633).

Would you mind uploading a tarball that contains the submodules as well? Over at standardese, I am using [git-archive-all](https://pypi.org/project/git-archive-all/) for this if you want to automate things: https://github.com/standardese/standardese/blob/master/rever.xsh#L36

**Comment by biojppm** [comment]
Thanks for reporting! I guess you are talking about the source tarball? That was created automatically by github; I have to investigate how that happens.

In the meantime, you can of course clone the tag with `git clone --recursive` but I guess you already know that.

**Comment by saraedum** [comment]
@biojppm yes, I was talking about the autogenerated tarballs. Afaik you cannot customize how github generates these.

All the (Linux) distributions I know, will strongly prefer to download an official tarball over a git checkout. Another option for you would be to create a c4core release. Then this would just be a dependency that needs to be installed to build rapidyaml. But currently, your cmake setup does not support such a setup I think.

**Comment by biojppm** [comment]
Definitely there is support for using an external c4core from outside the ryml repo; I do that in several other projects of mine.

I will write docs to explain how that is done, and maybe make that a little more evident also in the main cmake.

**Comment by saraedum** [comment]
> Definitely there is support for using an external c4core from outside the ryml repo; I do that in several other projects of mine.

https://github.com/biojppm/rapidyaml/blob/master/CMakeLists.txt#L2

It's not obvious how to do this, since you are explicitly referencing `ext/c4core`.

**Comment by biojppm** [comment]
Indeed, that's right. That line does require the c4core submodule to be checked out. I meant there is a way to use a different c4core for building.

**Comment by saraedum** [comment]
@biojppm is there anything I can do to help with resolving this issue?

I guess just uploading a new tarball would fix this for me for the moment. But I am not sure if you had further plans here related to the CMakeLists.txt setup.

**Comment by biojppm** [comment]
Sorry for the delay - it's been really busy.

I want to fix this in the GitHub action that uploads the artifacts, but I am a bit confused on how to go about this so I had to put it off. To fix your problem I will manually upload during this week, hopefully soon.

**Comment by biojppm** [comment]
The uploads are there: [tgz](https://github.com/biojppm/rapidyaml/releases/download/v0.1.0/ryml-0.1.0-src.tgz) and [zip](https://github.com/biojppm/rapidyaml/releases/download/v0.1.0/ryml-0.1.0-src.zip)

**Comment by biojppm** [comment]
I will keep this open until it's properly fixed in the action.

**Comment by saraedum** [comment]
Great. Thanks a lot.

> I will write docs to explain how that is done, and maybe make it a little more evident also in the main cmake.

Did you already have a chance to do that? Otherwise, should we track that in another issue?

**Comment by biojppm** [comment]
You're right, this was rushed and I forgot about it. I'll leave this open until that is done.

**Comment by biojppm** [comment]
@saraedum Finally got around to add the promised sample; have a look at the commit above to see how to do it.

FWIW, it is based in my c4 cmake wrappers, and thus a bit obscure -- but it does work.

HTH.

**Comment by biojppm** [comment]
Closing now; feel free to reopen if it is still unclear.
